# Optimizing Large DataFrames with Chunking

### Table of Contents
<a id="toc"></a>
1. [Introduction](#introduction)
2. [Set up](#set-up)
3. [Chunk Creation and Exploration](#chunk-exploration)
4. [Chunk Data Type Consistency](#chunk-consistency)
5. [Column Data Type Conversions](#column-conversions)
6. [Downcasting Experiment](#downcasting)
7. [Conclusion](#conclusion)

### Introduction
<a id="introduction"></a>
In this guided project, we will demonstrate how to chunk DataFrames and optimize memory usage. We are working with financial data from [Lending Club](https://www.lendingclub.com/), a company that manages peer-to-peer connections between borrowers and investors. While the original dataset is no longer hosted on the Lending Club website, it is available [on Kaggle](https://www.kaggle.com/datasets/wordsforthewise/lending-club/data). The Kaggle version covers 2007 to 2018; however, our dataset has been specifically tailored for this project to include data from 2007 to 2011.

To simulate a constrained environment, we will operate under the assumption that we only have **10 MB** of available memory. This constraint allows us to establish a clear "benchmark" for chunking our DataFrames effectively.

### Setup
<a id="set-up"></a>
We will begin by importing the necessary libraries and inspecting the first five rows of our dataset.

[Back to Table of Contents](#toc)

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display
pd.options.display.max_columns = 99

In [2]:
first_five = pd.read_csv('loans_2007.csv', nrows=5)
first_five

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,pub_rec_bankruptcies,tax_liens
0,1077501,1296599.0,5000.0,5000.0,4975.0,36 months,10.65%,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-2011,Fully Paid,n,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-1985,1.0,3.0,0.0,13648.0,83.7%,9.0,f,0.00,0.00,5863.155187,5833.84,5000.00,863.16,0.00,0.00,0.00,Jan-2015,171.62,Jun-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
1,1077430,1314167.0,2500.0,2500.0,2500.0,60 months,15.27%,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-2011,Charged Off,n,car,bike,309xx,GA,1.00,0.0,Apr-1999,5.0,3.0,0.0,1687.0,9.4%,4.0,f,0.00,0.00,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-2013,119.66,Sep-2013,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
2,1077175,1313524.0,2400.0,2400.0,2400.0,36 months,15.96%,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-2011,Fully Paid,n,small_business,real estate business,606xx,IL,8.72,0.0,Nov-2001,2.0,2.0,0.0,2956.0,98.5%,10.0,f,0.00,0.00,3005.666844,3005.67,2400.00,605.67,0.00,0.00,0.00,Jun-2014,649.91,Jun-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
3,1076863,1277178.0,10000.0,10000.0,10000.0,36 months,13.49%,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-2011,Fully Paid,n,other,personel,917xx,CA,20.00,0.0,Feb-1996,1.0,10.0,0.0,5598.0,21%,37.0,f,0.00,0.00,12231.890000,12231.89,10000.00,2214.92,16.97,0.00,0.00,Jan-2015,357.48,Apr-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
4,1075358,1311748.0,3000.0,3000.0,3000.0,60 months,12.69%,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-2011,Current,n,other,Personal,972xx,OR,17.94,0.0,Jan-1996,0.0,15.0,0.0,27783.0,53.9%,38.0,f,461.73,461.73,3581.120000,3581.12,2538.27,1042.85,0.00,0.00,0.00,Jun-2016,67.79,Jun-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0

### Chunk Creation and Exploration
<a id="chunk-exploration"></a>
With the environment set up and our initial data inspection complete, we need to address memory usage. To understand the footprint of our data, we will start by reading in a sample of 1,000 rows and calculating the memory consumption.

In [3]:
thousand_chunk = pd.read_csv('loans_2007.csv', nrows=1000)
print(thousand_chunk.memory_usage(deep=True).sum()/(1024*1024))

1.3676795959472656

The sample of 1,000 rows occupies only 1.4 MB of memory. Based on this, we can safely increase our chunk size to 3,000 rows. Let's examine the memory footprint across all 3,000-row chunks.

[Back to Table of Contents](#toc)

In [4]:
chunk_iter = pd.read_csv('loans_2007.csv', chunksize=3000)
for chunk in chunk_iter:
    print(chunk.memory_usage(deep=True).sum()/(1024*1024))

4.1016998291015625
4.098297119140625
4.099673271179199
4.1008806228637695
4.097287178039551
4.0987653732299805
4.097776412963867
4.09971809387207
4.097790718078613
4.097665786743164
4.110683441162109
4.10931396484375
4.115175247192383
4.326666831970215
0.7793684005737305

Now that we have defined our chunks, we want to analyze the specifics of each one to identify optimization opportunities. We will focus on:

* The data type (dtype) of each column.
* The number of unique values per column.
* The count of missing (null) values.
* The percentage of values that are unique.
* Float columns with no missing values that are candidates for conversion to integers.
* A sample of the first four values in each column to verify data formatting.

In [5]:
def profile_chunk(chunk):
    # Memory Footprint (in Megabytes)
    memory_mb = chunk.memory_usage(deep=True).sum() / (1024**2)

    profile_data = []

    for col in chunk.columns:
        # Basic stats
        dtype = chunk[col].dtype
        num_unique = chunk[col].nunique()
        total_rows = len(chunk)
        unique_pct = (num_unique / total_rows) * 100
        
        # Missing values check
        has_missing = chunk[col].isnull().any()
        missing_label = "Yes" if has_missing else "No"
        
        # Get the first 4 values as a comma-separated string
        samples = ", ".join(chunk[col].head(4).astype(str).tolist())
        
        # Integer Candidate check
        is_int_candidate = "No"
        if pd.api.types.is_float_dtype(dtype) and not has_missing:
            if (chunk[col] == chunk[col].apply(int)).all():
                is_int_candidate = "Yes"

        profile_data.append({
            "Column": col,
            "Dtype": dtype,
            "Uniq_Count": num_unique,
            "Uniq_Pct": f"{unique_pct:.2f}%",
            "Has_Missing": missing_label,
            "Int_Candidate": is_int_candidate,
            "Sample_Values": samples
        })

    # Create the summary DataFrame
    summary_df = pd.DataFrame(profile_data)
    
    return summary_df, memory_mb

In [6]:
chunk_iter = pd.read_csv('loans_2007.csv', chunksize=3000)
chunk_label = 1
total_memory = 0
for chunk in chunk_iter:
    print(f"Chunk {chunk_label}")
    chunk_summary, chunk_footprint = profile_chunk(chunk)
    print(f"Memory Footprint: {chunk_footprint:.4f} MB")
    
    display(chunk_summary) 

    chunk_label += 1
    total_memory += chunk_footprint
    print("\n")
    print("-"*85, "\n")

Chunk 1
Memory Footprint: 4.1017 MB

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,int64,3000,100.00%,No,No,"1077501, 1077430, 1077175, 1076863"
1,member_id,float64,3000,100.00%,No,Yes,"1296599.0, 1314167.0, 1313524.0, 1277178.0"
2,loan_amnt,float64,390,13.00%,No,Yes,"5000.0, 2500.0, 2400.0, 10000.0"
3,funded_amnt,float64,438,14.60%,No,Yes,"5000.0, 2500.0, 2400.0, 10000.0"
4,funded_amnt_inv,float64,663,22.10%,No,No,"4975.0, 2500.0, 2400.0, 10000.0"
5,term,object,2,0.07%,No,No,"36 months, 60 months, 36 months, 36 months"
6,int_rate,object,36,1.20%,No,No,"10.65%, 15.27%, 15.96%, 13.49%"
7,installment,float64,1591,53.03%,No,No,"162.87, 59.83, 84.33, 339.31"
8,grade,object,7,0.23%,No,No,"B, C, C, C"
9,sub_grade,object,35,1.17%,No,No,"B2, C4, C5, C1"
10,emp_title,object,2653,88.43%,Yes,No,"nan, Ryder, nan, AIR RESOURCES BOARD"
11,emp_length,object,11,0.37%,Yes,No,"10+ years, < 1 year, 10+ years, 10+ years"
12,home_ownership,object,3,0.10%,No,No,"RENT, RENT, RENT, RENT"
13,annual_inc,float64,641,21.37%,No,No,"24000.0, 30000.0, 12252.0, 49200.0"
14,verification_status,object,3,0.10%,No,No,"Verified, Source Verified, Not Verified, Sourc..."
15,issue_d,object,2,0.07%,No,No,"Dec-2011, Dec-2011, Dec-2011, Dec-2011"
16,loan_status,object,6,0.20%,No,No,"Fully Paid, Charged Off, Fully Paid, Fully Paid"
17,pymnt_plan,object,1,0.03%,No,No,"n, n, n, n"
18,purpose,object,13,0.43%,No,No,"credit_card, car, small_business, other"
19,title,object,1406,46.87%,No,No,"Computer, bike, real estate business, personel"
20,zip_code,object,568,18.93%,No,No,"860xx, 309xx, 606xx, 917xx"
21,addr_state,object,43,1.43%,No,No,"AZ, GA, IL, CA"
22,dti,float64,1717,57.23%,No,No,"27.65, 1.0, 8.72, 20.0"
23,delinq_2yrs,float64,5,0.17%,No,Yes,"0.0, 0.0, 0.0, 0.0"
24,earliest_cr_line,object,366,12.20%,No,No,"Jan-1985, Apr-1999, Nov-2001, Feb-1996"
25,inq_last_6mths,float64,9,0.30%,No,Yes,"1.0, 5.0, 2.0, 1.0"
26,open_acc,float64,29,0.97%,No,Yes,"3.0, 3.0, 2.0, 10.0"
27,pub_rec,float64,2,0.07%,No,Yes,"0.0, 0.0, 0.0, 0.0"
28,revol_bal,float64,2829,94.30%,No,Yes,"13648.0, 1687.0, 2956.0, 5598.0"
29,revol_util,object,884,29.47%,No,No,"83.7%, 9.4%, 98.5%, 21%"
30,total_acc,float64,62,2.07%,No,Yes,"9.0, 4.0, 10.0, 37.0"
31,initial_list_status,object,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float64,242,8.07%,No,No,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,242,8.07%,No,No,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,2985,99.50%,No,No,"5863.1551866952, 1008.71, 3005.6668441393, 122..."
35,total_pymnt_inv,float64,2801,93.37%,No,No,"5833.84, 1008.71, 3005.67, 12231.89"
36,total_rec_prncp,float64,1110,37.00%,No,No,"5000.0, 456.46, 2400.0, 10000.0"
37,total_rec_int,float64,2750,91.67%,No,No,"863.16, 435.17, 605.67, 2214.92"
38,total_rec_late_fee,float64,110,3.67%,No,No,"0.0, 0.0, 0.0, 16.97"
39,recoveries,float64,411,13.70%,No,No,"0.0, 117.08, 0.0, 0.0"
40,collection_recovery_fee,float64,364,12.13%,No,No,"0.0, 1.11, 0.0, 0.0"
41,last_pymnt_d,object,54,1.80%,Yes,No,"Jan-2015, Apr-2013, Jun-2014, Jan-2015"
42,last_pymnt_amnt,float64,2847,94.90%,No,No,"171.62, 119.66, 649.91, 357.48"
43,last_credit_pull_d,object,55,1.83%,No,No,"Jun-2016, Sep-2013, Jun-2016, Apr-2016"
44,collections_12_mths_ex_med,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.03%,No,Yes,"1.0, 1.0, 1.0, 1.0"
46,application_type,object,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,2,0.07%,No,Yes,"0.0, 0.0, 0.0, 0.0"
51,tax_liens,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"

-------------------------------------------------------------------------------------

Chunk 2
Memory Footprint: 4.0983 MB

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,int64,3000,100.00%,No,No,"1026242, 1027822, 1022057, 1027992"
1,member_id,float64,3000,100.00%,No,Yes,"1255399.0, 1257204.0, 1250835.0, 1257369.0"
2,loan_amnt,float64,397,13.23%,No,Yes,"35000.0, 1800.0, 16000.0, 3000.0"
3,funded_amnt,float64,397,13.23%,No,Yes,"35000.0, 1800.0, 16000.0, 3000.0"
4,funded_amnt_inv,float64,667,22.23%,No,No,"34647.35244739579, 1800.0, 16000.0, 3000.0"
5,term,object,2,0.07%,No,No,"60 months, 36 months, 36 months, 36 months"
6,int_rate,object,36,1.20%,No,No,"17.27%, 7.51%, 17.27%, 12.42%"
7,installment,float64,1541,51.37%,No,No,"874.93, 56.0, 572.6, 100.25"
8,grade,object,7,0.23%,No,No,"D, A, D, B"
9,sub_grade,object,35,1.17%,No,No,"D3, A3, D3, B4"
10,emp_title,object,2588,86.27%,Yes,No,"Department Of Homeland Security, City of Madis..."
11,emp_length,object,11,0.37%,Yes,No,"5 years, 10+ years, 10+ years, 5 years"
12,home_ownership,object,3,0.10%,No,No,"MORTGAGE, MORTGAGE, RENT, RENT"
13,annual_inc,float64,739,24.63%,No,No,"97936.0, 58000.0, 63336.0, 90000.0"
14,verification_status,object,3,0.10%,No,No,"Verified, Not Verified, Source Verified, Not V..."
15,issue_d,object,3,0.10%,No,No,"Nov-2011, Nov-2011, Nov-2011, Nov-2011"
16,loan_status,object,6,0.20%,No,No,"Charged Off, Fully Paid, Fully Paid, Fully Paid"
17,pymnt_plan,object,1,0.03%,No,No,"n, n, n, n"
18,purpose,object,13,0.43%,No,No,"debt_consolidation, car, debt_consolidation, o..."
19,title,object,1454,48.47%,No,No,"Debt Consolidation, Jeep Comanche, Consolidati..."
20,zip_code,object,570,19.00%,No,No,"221xx, 424xx, 802xx, 070xx"
21,addr_state,object,45,1.50%,No,No,"VA, KY, CO, NJ"
22,dti,float64,1751,58.37%,No,No,"23.84, 26.92, 17.24, 6.25"
23,delinq_2yrs,float64,7,0.23%,No,Yes,"0.0, 0.0, 0.0, 0.0"
24,earliest_cr_line,object,399,13.30%,No,No,"Feb-1989, Jan-1992, Jun-1998, Nov-2003"
25,inq_last_6mths,float64,8,0.27%,No,Yes,"0.0, 0.0, 1.0, 1.0"
26,open_acc,float64,30,1.00%,No,Yes,"18.0, 10.0, 24.0, 15.0"
27,pub_rec,float64,3,0.10%,No,Yes,"0.0, 0.0, 0.0, 0.0"
28,revol_bal,float64,2810,93.67%,No,Yes,"32185.0, 10141.0, 14619.0, 13300.0"
29,revol_util,object,951,31.70%,Yes,No,"36.6%, 48.1%, 54.8%, 75.7%"
30,total_acc,float64,61,2.03%,No,Yes,"35.0, 28.0, 34.0, 22.0"
31,initial_list_status,object,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float64,245,8.17%,No,No,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,244,8.13%,No,No,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,2995,99.83%,No,No,"11373.240000000002, 2012.5175278858, 20493.848..."
35,total_pymnt_inv,float64,2856,95.20%,No,No,"11253.22, 2012.52, 20493.85, 3608.82"
36,total_rec_prncp,float64,1058,35.27%,No,No,"5252.6, 1800.0, 16000.0, 3000.0"
37,total_rec_int,float64,2790,93.00%,No,No,"6120.64, 212.52, 4493.85, 608.82"
38,total_rec_late_fee,float64,127,4.23%,No,No,"0.0, 0.0, 0.0, 0.0"
39,recoveries,float64,375,12.50%,No,No,"0.0, 0.0, 0.0, 0.0"
40,collection_recovery_fee,float64,324,10.80%,No,No,"0.0, 0.0, 0.0, 0.0"
41,last_pymnt_d,object,56,1.87%,Yes,No,"Feb-2013, Aug-2014, Jul-2014, Dec-2014"
42,last_pymnt_amnt,float64,2841,94.70%,No,No,"30.21, 278.09, 3324.63, 101.91"
43,last_credit_pull_d,object,57,1.90%,No,No,"Jun-2016, Jun-2016, Jan-2016, Feb-2016"
44,collections_12_mths_ex_med,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.03%,No,Yes,"1.0, 1.0, 1.0, 1.0"
46,application_type,object,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,3,0.10%,No,Yes,"0.0, 0.0, 0.0, 0.0"
51,tax_liens,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"

-------------------------------------------------------------------------------------

Chunk 3
Memory Footprint: 4.0997 MB

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,int64,3000,100.00%,No,No,"867360, 976782, 976611, 976592"
1,member_id,float64,3000,100.00%,No,Yes,"1080956.0, 1199531.0, 1199373.0, 1199353.0"
2,loan_amnt,float64,395,13.17%,No,Yes,"9000.0, 24000.0, 1000.0, 2400.0"
3,funded_amnt,float64,474,15.80%,No,Yes,"9000.0, 24000.0, 1000.0, 2400.0"
4,funded_amnt_inv,float64,829,27.63%,No,No,"8900.0, 23925.0, 1000.0, 2400.0"
5,term,object,2,0.07%,No,No,"36 months, 60 months, 36 months, 36 months"
6,int_rate,object,66,2.20%,No,No,"6.03%, 14.65%, 7.51%, 17.58%"
7,installment,float64,1943,64.77%,No,No,"273.92, 566.56, 31.12, 86.27"
8,grade,object,7,0.23%,No,No,"A, C, A, D"
9,sub_grade,object,34,1.13%,No,No,"A1, C3, A3, D4"
10,emp_title,object,2592,86.40%,Yes,No,"Thomson Reuters, Ernst & Young, Stonehenge Adv..."
11,emp_length,object,11,0.37%,Yes,No,"8 years, 10+ years, < 1 year, 10+ years"
12,home_ownership,object,3,0.10%,No,No,"MORTGAGE, MORTGAGE, RENT, MORTGAGE"
13,annual_inc,float64,752,25.07%,No,No,"77000.0, 100000.0, 30000.0, 31200.0"
14,verification_status,object,3,0.10%,No,No,"Not Verified, Verified, Source Verified, Sourc..."
15,issue_d,object,3,0.10%,No,No,"Oct-2011, Oct-2011, Oct-2011, Oct-2011"
16,loan_status,object,5,0.17%,No,No,"Fully Paid, Charged Off, Fully Paid, Charged Off"
17,pymnt_plan,object,1,0.03%,No,No,"n, n, n, n"
18,purpose,object,13,0.43%,No,No,"home_improvement, credit_card, moving, medical"
19,title,object,1464,48.80%,No,No,"Home Improvement Loan, Help me get out of debt..."
20,zip_code,object,571,19.03%,No,No,"553xx, 070xx, 080xx, 201xx"
21,addr_state,object,43,1.43%,No,No,"MN, NJ, NJ, VA"
22,dti,float64,1789,59.63%,No,No,"9.86, 18.85, 0.6, 6.31"
23,delinq_2yrs,float64,6,0.20%,No,Yes,"0.0, 0.0, 0.0, 1.0"
24,earliest_cr_line,object,401,13.37%,No,No,"Apr-1999, Jan-1999, Apr-1977, Sep-1994"
25,inq_last_6mths,float64,9,0.30%,No,Yes,"1.0, 3.0, 1.0, 2.0"
26,open_acc,float64,28,0.93%,No,Yes,"11.0, 6.0, 4.0, 4.0"
27,pub_rec,float64,3,0.10%,No,Yes,"0.0, 0.0, 0.0, 0.0"
28,revol_bal,float64,2752,91.73%,No,Yes,"10526.0, 15293.0, 504.0, 5112.0"
29,revol_util,object,951,31.70%,No,No,"19.7%, 71.8%, 18%, 98.3%"
30,total_acc,float64,61,2.03%,No,Yes,"27.0, 29.0, 5.0, 7.0"
31,initial_list_status,object,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float64,222,7.40%,No,No,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,223,7.43%,No,No,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,2995,99.83%,No,No,"9720.49484418, 8046.030000000028, 1111.5001638..."
35,total_pymnt_inv,float64,2917,97.23%,No,No,"9612.49, 8020.96, 1111.5, 503.88"
36,total_rec_prncp,float64,1027,34.23%,No,No,"9000.0, 3512.61, 1000.0, 262.02"
37,total_rec_int,float64,2843,94.77%,No,No,"720.49, 3299.7, 111.5, 167.48"
38,total_rec_late_fee,float64,114,3.80%,No,No,"0.0, 56.605870297967, 0.0, 0.0"
39,recoveries,float64,332,11.07%,No,No,"0.0, 1177.12, 0.0, 74.38"
40,collection_recovery_fee,float64,291,9.70%,No,No,"0.0, 11.5, 0.0, 0.81"
41,last_pymnt_d,object,57,1.90%,Yes,No,"Aug-2013, Oct-2012, Jan-2014, Mar-2012"
42,last_pymnt_amnt,float64,2919,97.30%,No,No,"3970.06, 1133.12, 307.07, 86.27"
43,last_credit_pull_d,object,59,1.97%,No,No,"Aug-2013, Apr-2015, Jan-2014, Aug-2012"
44,collections_12_mths_ex_med,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.03%,No,Yes,"1.0, 1.0, 1.0, 1.0"
46,application_type,object,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,3,0.10%,No,Yes,"0.0, 0.0, 0.0, 0.0"
51,tax_liens,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"

-------------------------------------------------------------------------------------

Chunk 4
Memory Footprint: 4.1009 MB

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,int64,3000,100.00%,No,No,"857120, 758907, 846262, 855781"
1,member_id,float64,3000,100.00%,No,Yes,"1069550.0, 959119.0, 1057637.0, 1068118.0"
2,loan_amnt,float64,411,13.70%,No,Yes,"12000.0, 2000.0, 14400.0, 10000.0"
3,funded_amnt,float64,490,16.33%,No,Yes,"12000.0, 2000.0, 14400.0, 10000.0"
4,funded_amnt_inv,float64,817,27.23%,No,No,"12000.0, 2000.0, 14400.0, 10000.0"
5,term,object,2,0.07%,No,No,"60 months, 36 months, 60 months, 36 months"
6,int_rate,object,37,1.23%,No,No,"18.39%, 10.99%, 13.49%, 5.42%"
7,installment,float64,1695,56.50%,No,No,"307.28, 65.47, 331.27, 301.6"
8,grade,object,7,0.23%,No,No,"E, B, C, A"
9,sub_grade,object,35,1.17%,No,No,"E2, B3, C2, A1"
10,emp_title,object,2598,86.60%,Yes,No,"Effingham County Middle School, Catalyst Healt..."
11,emp_length,object,11,0.37%,Yes,No,"10+ years, 3 years, 3 years, 4 years"
12,home_ownership,object,3,0.10%,No,No,"OWN, MORTGAGE, MORTGAGE, RENT"
13,annual_inc,float64,788,26.27%,No,No,"67000.0, 56000.0, 62000.0, 42000.0"
14,verification_status,object,3,0.10%,No,No,"Source Verified, Verified, Not Verified, Not V..."
15,issue_d,object,3,0.10%,No,No,"Aug-2011, Aug-2011, Aug-2011, Aug-2011"
16,loan_status,object,6,0.20%,No,No,"Fully Paid, Fully Paid, Current, Fully Paid"
17,pymnt_plan,object,1,0.03%,No,No,"n, n, n, n"
18,purpose,object,13,0.43%,No,No,"debt_consolidation, moving, home_improvement, ..."
19,title,object,1511,50.37%,No,No,"Debt Consolidation, Moving, Home Improvement L..."
20,zip_code,object,559,18.63%,No,No,"304xx, 326xx, 276xx, 347xx"
21,addr_state,object,43,1.43%,No,No,"GA, FL, NC, FL"
22,dti,float64,1768,58.93%,No,No,"19.34, 16.86, 9.27, 6.63"
23,delinq_2yrs,float64,6,0.20%,No,Yes,"0.0, 0.0, 0.0, 0.0"
24,earliest_cr_line,object,383,12.77%,No,No,"Aug-1993, Jul-1996, Sep-2002, Sep-1996"
25,inq_last_6mths,float64,8,0.27%,No,Yes,"1.0, 1.0, 1.0, 0.0"
26,open_acc,float64,32,1.07%,No,Yes,"8.0, 11.0, 9.0, 14.0"
27,pub_rec,float64,3,0.10%,No,Yes,"0.0, 0.0, 0.0, 0.0"
28,revol_bal,float64,2736,91.20%,No,Yes,"16455.0, 17268.0, 5878.0, 8199.0"
29,revol_util,object,939,31.30%,Yes,No,"95.1%, 49.4%, 27.3%, 28%"
30,total_acc,float64,61,2.03%,No,Yes,"15.0, 19.0, 21.0, 18.0"
31,initial_list_status,object,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float64,208,6.93%,No,No,"0.0, 0.0, 991.88, 0.0"
33,out_prncp_inv,float64,208,6.93%,No,No,"0.0, 0.0, 991.88, 0.0"
34,total_pymnt,float64,2993,99.77%,No,No,"15696.4014583245, 2260.8390477103, 18848.75, 1..."
35,total_pymnt_inv,float64,2856,95.20%,No,No,"15696.4, 2260.84, 18848.75, 10857.53"
36,total_rec_prncp,float64,1047,34.90%,No,No,"12000.0, 2000.0, 13408.12, 10000.0"
37,total_rec_int,float64,2743,91.43%,No,No,"3696.4, 260.84, 5440.63, 857.53"
38,total_rec_late_fee,float64,116,3.87%,No,No,"0.0, 0.0, 0.0, 0.0"
39,recoveries,float64,352,11.73%,No,No,"0.0, 0.0, 0.0, 0.0"
40,collection_recovery_fee,float64,284,9.47%,No,No,"0.0, 0.0, 0.0, 0.0"
41,last_pymnt_d,object,59,1.97%,Yes,No,"Aug-2013, Mar-2013, Jun-2016, Sep-2014"
42,last_pymnt_amnt,float64,2894,96.47%,No,No,"8937.72, 1154.35, 331.27, 309.42"
43,last_credit_pull_d,object,59,1.97%,No,No,"Aug-2013, Feb-2014, Jun-2016, Sep-2014"
44,collections_12_mths_ex_med,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.03%,No,Yes,"1.0, 1.0, 1.0, 1.0"
46,application_type,object,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,2,0.07%,No,Yes,"0.0, 0.0, 0.0, 0.0"
51,tax_liens,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"

-------------------------------------------------------------------------------------

Chunk 5
Memory Footprint: 4.0973 MB

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,int64,3000,100.00%,No,No,"805706, 805692, 805663, 805646"
1,member_id,float64,3000,100.00%,No,Yes,"1011777.0, 1011761.0, 1011728.0, 1011709.0"
2,loan_amnt,float64,416,13.87%,No,Yes,"10000.0, 14000.0, 35000.0, 4800.0"
3,funded_amnt,float64,516,17.20%,No,Yes,"10000.0, 14000.0, 35000.0, 4800.0"
4,funded_amnt_inv,float64,733,24.43%,No,No,"10000.0, 13750.0, 34975.0, 4800.0"
5,term,object,2,0.07%,No,No,"36 months, 36 months, 60 months, 36 months"
6,int_rate,object,73,2.43%,No,No,"16.89%, 8.49%, 12.99%, 5.42%"
7,installment,float64,1765,58.83%,No,No,"355.99, 441.89, 796.18, 144.77"
8,grade,object,7,0.23%,No,No,"D, A, C, A"
9,sub_grade,object,35,1.17%,No,No,"D4, A5, C1, A1"
10,emp_title,object,2590,86.33%,Yes,No,"USAF, Bacik Group LLC, nan, CONNSACS, Inc."
11,emp_length,object,11,0.37%,Yes,No,"10+ years, < 1 year, 10+ years, 3 years"
12,home_ownership,object,4,0.13%,No,No,"MORTGAGE, MORTGAGE, RENT, RENT"
13,annual_inc,float64,746,24.87%,No,No,"49000.0, 65000.0, 45000.0, 35000.0"
14,verification_status,object,3,0.10%,No,No,"Source Verified, Verified, Verified, Not Verified"
15,issue_d,object,3,0.10%,No,No,"Jul-2011, Jul-2011, Jul-2011, Jul-2011"
16,loan_status,object,6,0.20%,No,No,"Fully Paid, Fully Paid, Fully Paid, Fully Paid"
17,pymnt_plan,object,1,0.03%,No,No,"n, n, n, n"
18,purpose,object,13,0.43%,No,No,"debt_consolidation, debt_consolidation, small_..."
19,title,object,1610,53.67%,No,No,"Pay this off, Debt Consolidation Loan, Small B..."
20,zip_code,object,568,18.93%,No,No,"782xx, 336xx, 117xx, 067xx"
21,addr_state,object,43,1.43%,No,No,"TX, FL, NY, CT"
22,dti,float64,1787,59.57%,No,No,"19.98, 27.55, 11.84, 12.82"
23,delinq_2yrs,float64,7,0.23%,No,Yes,"1.0, 0.0, 0.0, 0.0"
24,earliest_cr_line,object,391,13.03%,No,No,"Sep-2000, Aug-2001, Jun-1999, Apr-2000"
25,inq_last_6mths,float64,9,0.30%,No,Yes,"0.0, 0.0, 0.0, 0.0"
26,open_acc,float64,30,1.00%,No,Yes,"7.0, 8.0, 4.0, 10.0"
27,pub_rec,float64,4,0.13%,No,Yes,"0.0, 0.0, 0.0, 0.0"
28,revol_bal,float64,2738,91.27%,No,Yes,"4638.0, 10378.0, 0.0, 3556.0"
29,revol_util,object,949,31.63%,Yes,No,"72.5%, 42.4%, 0%, 15.4%"
30,total_acc,float64,63,2.10%,No,Yes,"20.0, 26.0, 8.0, 15.0"
31,initial_list_status,object,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float64,92,3.07%,No,No,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,92,3.07%,No,No,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,2993,99.77%,No,No,"12259.6822311238, 15548.233279997, 40793.11137..."
35,total_pymnt_inv,float64,2821,94.03%,No,No,"12259.68, 15270.59, 40763.97, 4965.67"
36,total_rec_prncp,float64,987,32.90%,No,No,"10000.0, 14000.0, 35000.0, 4800.0"
37,total_rec_int,float64,2746,91.53%,No,No,"2259.68, 1548.23, 5793.11, 165.67"
38,total_rec_late_fee,float64,118,3.93%,No,No,"0.0, 0.0, 0.0, 0.0"
39,recoveries,float64,360,12.00%,No,No,"0.0, 0.0, 0.0, 0.0"
40,collection_recovery_fee,float64,297,9.90%,No,No,"0.0, 0.0, 0.0, 0.0"
41,last_pymnt_d,object,60,2.00%,Yes,No,"Apr-2013, Apr-2013, Dec-2012, Jul-2012"
42,last_pymnt_amnt,float64,2917,97.23%,No,No,"5159.26, 6731.57, 28069.18, 1052.34"
43,last_credit_pull_d,object,61,2.03%,No,No,"Jan-2014, Aug-2014, Jan-2014, Jan-2016"
44,collections_12_mths_ex_med,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.03%,No,Yes,"1.0, 1.0, 1.0, 1.0"
46,application_type,object,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,3,0.10%,No,Yes,"0.0, 0.0, 0.0, 0.0"
51,tax_liens,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"

-------------------------------------------------------------------------------------

Chunk 6
Memory Footprint: 4.0988 MB

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,int64,3000,100.00%,No,No,"756869, 756858, 756867, 754104"
1,member_id,float64,3000,100.00%,No,Yes,"956839.0, 956827.0, 956834.0, 953803.0"
2,loan_amnt,float64,357,11.90%,No,Yes,"12800.0, 3000.0, 6000.0, 19125.0"
3,funded_amnt,float64,417,13.90%,No,Yes,"12800.0, 3000.0, 6000.0, 11825.0"
4,funded_amnt_inv,float64,769,25.63%,No,No,"12800.0, 3000.0, 5975.0, 11825.0"
5,term,object,2,0.07%,No,No,"60 months, 60 months, 36 months, 60 months"
6,int_rate,object,68,2.27%,No,No,"17.49%, 14.79%, 11.49%, 21.36%"
7,installment,float64,1953,65.10%,No,No,"321.5, 71.04, 197.83, 322.31"
8,grade,object,7,0.23%,No,No,"D, C, B, F"
9,sub_grade,object,35,1.17%,No,No,"D5, C4, B4, F4"
10,emp_title,object,2648,88.27%,Yes,No,"CVS, General Beer, Pleasant View Home, Norther..."
11,emp_length,object,11,0.37%,Yes,No,"9 years, 5 years, 4 years, 10+ years"
12,home_ownership,object,3,0.10%,No,No,"MORTGAGE, MORTGAGE, MORTGAGE, MORTGAGE"
13,annual_inc,float64,831,27.70%,No,No,"204000.0, 42000.0, 40800.0, 75000.0"
14,verification_status,object,3,0.10%,No,No,"Verified, Not Verified, Not Verified, Verified"
15,issue_d,object,3,0.10%,No,No,"May-2011, May-2011, May-2011, May-2011"
16,loan_status,object,4,0.13%,No,No,"Fully Paid, Fully Paid, Fully Paid, Fully Paid"
17,pymnt_plan,object,1,0.03%,No,No,"n, n, n, n"
18,purpose,object,13,0.43%,No,No,"car, home_improvement, wedding, home_improvement"
19,title,object,1775,59.17%,No,No,"Car loan for my graduate, Loan, wedding, home ..."
20,zip_code,object,578,19.27%,No,No,"301xx, 547xx, 675xx, 109xx"
21,addr_state,object,43,1.43%,No,No,"GA, WI, KS, NY"
22,dti,float64,1748,58.27%,No,No,"16.95, 2.51, 4.06, 18.22"
23,delinq_2yrs,float64,10,0.33%,No,Yes,"0.0, 0.0, 0.0, 2.0"
24,earliest_cr_line,object,383,12.77%,No,No,"Sep-1989, Mar-1994, Jun-1995, Jul-1993"
25,inq_last_6mths,float64,7,0.23%,No,Yes,"1.0, 2.0, 1.0, 0.0"
26,open_acc,float64,29,0.97%,No,Yes,"21.0, 8.0, 5.0, 13.0"
27,pub_rec,float64,4,0.13%,No,Yes,"0.0, 0.0, 1.0, 0.0"
28,revol_bal,float64,2744,91.47%,No,Yes,"80417.0, 4709.0, 5512.0, 48141.0"
29,revol_util,object,956,31.87%,No,No,"85.3%, 47.1%, 52.5%, 28.5%"
30,total_acc,float64,63,2.10%,No,Yes,"56.0, 24.0, 14.0, 45.0"
31,initial_list_status,object,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float64,5,0.17%,No,No,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,5,0.17%,No,No,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,2992,99.73%,No,No,"17947.76254002, 4262.3579286201, 7121.77332817..."
35,total_pymnt_inv,float64,2903,96.77%,No,No,"17947.76, 4262.36, 7092.1, 17428.84"
36,total_rec_prncp,float64,835,27.83%,No,No,"12800.0, 3000.0, 6000.0, 11825.0"
37,total_rec_int,float64,2814,93.80%,No,No,"5147.76, 1262.36, 1121.77, 5603.84"
38,total_rec_late_fee,float64,131,4.37%,No,No,"0.0, 0.0, 0.0, 0.0"
39,recoveries,float64,340,11.33%,No,No,"0.0, 0.0, 0.0, 0.0"
40,collection_recovery_fee,float64,291,9.70%,No,No,"0.0, 0.0, 0.0, 0.0"
41,last_pymnt_d,object,62,2.07%,Yes,No,"Apr-2014, Jun-2016, Jun-2014, Aug-2014"
42,last_pymnt_amnt,float64,2939,97.97%,No,No,"7055.77, 70.99, 214.37, 133.26"
43,last_credit_pull_d,object,62,2.07%,No,No,"Jun-2016, May-2016, Jun-2016, Jul-2014"
44,collections_12_mths_ex_med,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.03%,No,Yes,"1.0, 1.0, 1.0, 1.0"
46,application_type,object,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,2,0.07%,No,Yes,"0.0, 0.0, 1.0, 0.0"
51,tax_liens,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"

-------------------------------------------------------------------------------------

Chunk 7
Memory Footprint: 4.0978 MB

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,int64,3000,100.00%,No,No,"707798, 707767, 707784, 707414"
1,member_id,float64,3000,100.00%,No,Yes,"900184.0, 900150.0, 900169.0, 899761.0"
2,loan_amnt,float64,336,11.20%,No,Yes,"2250.0, 19000.0, 20000.0, 16000.0"
3,funded_amnt,float64,342,11.40%,No,Yes,"2250.0, 19000.0, 20000.0, 16000.0"
4,funded_amnt_inv,float64,832,27.73%,No,No,"2225.0, 18950.0, 19892.28417160136, 16000.0"
5,term,object,2,0.07%,No,No,"36 months, 60 months, 60 months, 60 months"
6,int_rate,object,45,1.50%,No,No,"5.42%, 10.37%, 15.65%, 17.14%"
7,installment,float64,1546,51.53%,No,No,"67.86, 407.17, 482.65, 398.85"
8,grade,object,7,0.23%,No,No,"A, B, D, E"
9,sub_grade,object,35,1.17%,No,No,"A1, B3, D4, E3"
10,emp_title,object,2600,86.67%,Yes,No,"Corporate Care, Lake Region Medical, CSS Techn..."
11,emp_length,object,11,0.37%,Yes,No,"nan, 2 years, < 1 year, 9 years"
12,home_ownership,object,3,0.10%,No,No,"RENT, MORTGAGE, OWN, MORTGAGE"
13,annual_inc,float64,780,26.00%,No,No,"52500.0, 130000.0, 80640.0, 52000.0"
14,verification_status,object,3,0.10%,No,No,"Not Verified, Not Verified, Verified, Verified"
15,issue_d,object,4,0.13%,No,No,"Mar-2011, Mar-2011, Mar-2011, Mar-2011"
16,loan_status,object,4,0.13%,No,No,"Fully Paid, Fully Paid, Fully Paid, Fully Paid"
17,pymnt_plan,object,1,0.03%,No,No,"n, n, n, n"
18,purpose,object,13,0.43%,No,No,"debt_consolidation, debt_consolidation, debt_c..."
19,title,object,1958,65.27%,No,No,"Debt consolidation 6 month goal, Consolidation..."
20,zip_code,object,551,18.37%,No,No,"945xx, 554xx, 190xx, 778xx"
21,addr_state,object,43,1.43%,No,No,"CA, MN, PA, TX"
22,dti,float64,1728,57.60%,No,No,"16.43, 12.95, 20.6, 12.14"
23,delinq_2yrs,float64,10,0.33%,No,Yes,"0.0, 0.0, 0.0, 0.0"
24,earliest_cr_line,object,385,12.83%,No,No,"Apr-1992, Dec-1990, Aug-1992, Jun-1999"
25,inq_last_6mths,float64,9,0.30%,No,Yes,"0.0, 0.0, 2.0, 0.0"
26,open_acc,float64,32,1.07%,No,Yes,"9.0, 12.0, 12.0, 24.0"
27,pub_rec,float64,3,0.10%,No,Yes,"0.0, 0.0, 0.0, 0.0"
28,revol_bal,float64,2760,92.00%,No,Yes,"4425.0, 35392.0, 13135.0, 18170.0"
29,revol_util,object,948,31.60%,Yes,No,"36%, 32.6%, 61.5%, 34%"
30,total_acc,float64,64,2.13%,No,Yes,"25.0, 34.0, 33.0, 53.0"
31,initial_list_status,object,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float64,4,0.13%,No,No,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,4,0.13%,No,No,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,2994,99.80%,No,No,"2442.28936694, 22099.2429278712, 25009.1116506..."
35,total_pymnt_inv,float64,2935,97.83%,No,No,"2415.15, 22041.09, 24776.25, 23913.81"
36,total_rec_prncp,float64,785,26.17%,No,No,"2250.0, 19000.0, 20000.0, 16000.0"
37,total_rec_int,float64,2856,95.20%,No,No,"192.29, 3099.24, 5009.11, 7893.87"
38,total_rec_late_fee,float64,125,4.17%,No,No,"0.0, 0.0, 0.0, 19.94"
39,recoveries,float64,314,10.47%,No,No,"0.0, 0.0, 0.0, 0.0"
40,collection_recovery_fee,float64,260,8.67%,No,No,"0.0, 0.0, 0.0, 0.0"
41,last_pymnt_d,object,64,2.13%,Yes,No,"Feb-2014, Feb-2013, Feb-2013, Mar-2016"
42,last_pymnt_amnt,float64,2920,97.33%,No,No,"208.76, 13561.62, 14885.24, 160.57"
43,last_credit_pull_d,object,65,2.17%,No,No,"Mar-2016, May-2016, Feb-2013, Mar-2016"
44,collections_12_mths_ex_med,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.03%,No,Yes,"1.0, 1.0, 1.0, 1.0"
46,application_type,object,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,3,0.10%,No,Yes,"0.0, 0.0, 0.0, 0.0"
51,tax_liens,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"

-------------------------------------------------------------------------------------

Chunk 8
Memory Footprint: 4.0997 MB

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,int64,3000,100.00%,No,No,"647327, 649790, 649929, 649256"
1,member_id,float64,3000,100.00%,No,Yes,"828194.0, 831250.0, 831420.0, 830639.0"
2,loan_amnt,float64,282,9.40%,No,Yes,"5000.0, 6250.0, 7000.0, 10000.0"
3,funded_amnt,float64,484,16.13%,No,Yes,"5000.0, 6250.0, 7000.0, 10000.0"
4,funded_amnt_inv,float64,1001,33.37%,No,No,"5000.0, 6233.993329186118, 6500.0, 10000.0"
5,term,object,2,0.07%,No,No,"36 months, 36 months, 36 months, 36 months"
6,int_rate,object,65,2.17%,No,No,"7.29%, 5.79%, 10.74%, 16.40%"
7,installment,float64,1783,59.43%,No,No,"155.05, 189.55, 228.32, 353.55"
8,grade,object,7,0.23%,No,No,"A, A, B, E"
9,sub_grade,object,35,1.17%,No,No,"A4, A2, B4, E1"
10,emp_title,object,2497,83.23%,Yes,No,"Wachovia, Services at Brookside, Pacific Marin..."
11,emp_length,object,11,0.37%,Yes,No,"< 1 year, 2 years, 10+ years, 4 years"
12,home_ownership,object,3,0.10%,No,No,"RENT, MORTGAGE, MORTGAGE, RENT"
13,annual_inc,float64,723,24.10%,No,No,"16800.0, 46500.0, 73000.0, 100000.0"
14,verification_status,object,3,0.10%,No,No,"Source Verified, Verified, Not Verified, Verified"
15,issue_d,object,3,0.10%,No,No,"Jan-2011, Jan-2011, Jan-2011, Jan-2011"
16,loan_status,object,3,0.10%,No,No,"Fully Paid, Fully Paid, Charged Off, Fully Paid"
17,pymnt_plan,object,1,0.03%,No,No,"n, n, n, n"
18,purpose,object,13,0.43%,No,No,"debt_consolidation, small_business, debt_conso..."
19,title,object,1919,63.97%,No,No,"Another step toward freedom, Paying off cards ..."
20,zip_code,object,558,18.60%,No,No,"327xx, 195xx, 920xx, 088xx"
21,addr_state,object,43,1.43%,No,No,"FL, PA, CA, NJ"
22,dti,float64,1629,54.30%,No,No,"9.5, 3.33, 17.24, 7.94"
23,delinq_2yrs,float64,6,0.20%,No,Yes,"0.0, 0.0, 0.0, 0.0"
24,earliest_cr_line,object,387,12.90%,No,No,"May-2004, Sep-2004, Jun-1987, Aug-2006"
25,inq_last_6mths,float64,8,0.27%,No,Yes,"0.0, 0.0, 0.0, 3.0"
26,open_acc,float64,28,0.93%,No,Yes,"5.0, 8.0, 10.0, 7.0"
27,pub_rec,float64,4,0.13%,No,Yes,"0.0, 0.0, 0.0, 0.0"
28,revol_bal,float64,2673,89.10%,No,Yes,"3041.0, 6453.0, 20010.0, 5015.0"
29,revol_util,object,952,31.73%,Yes,No,"35.8%, 27.3%, 98.6%, 79.6%"
30,total_acc,float64,61,2.03%,No,Yes,"11.0, 14.0, 30.0, 16.0"
31,initial_list_status,object,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float64,2,0.07%,No,No,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,2,0.07%,No,No,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,2997,99.90%,No,No,"5500.9162680574, 6823.706425300299, 5479.49, 1..."
35,total_pymnt_inv,float64,2981,99.37%,No,No,"5500.92, 6805.71, 5087.47, 12334.91"
36,total_rec_prncp,float64,864,28.80%,No,No,"5000.0, 6250.0, 4404.21, 10000.0"
37,total_rec_int,float64,2944,98.13%,No,No,"500.92, 573.71, 1063.95, 2317.23"
38,total_rec_late_fee,float64,154,5.13%,No,No,"0.0, 0.0, 0.0, 17.680000000353"
39,recoveries,float64,270,9.00%,No,No,"0.0, 0.0, 11.33, 0.0"
40,collection_recovery_fee,float64,218,7.27%,No,No,"0.0, 0.0, 0.0, 0.0"
41,last_pymnt_d,object,65,2.17%,Yes,No,"Jan-2013, Jan-2014, Jan-2013, Dec-2012"
42,last_pymnt_amnt,float64,2950,98.33%,No,No,"300.88, 228.39, 228.32, 4551.95"
43,last_credit_pull_d,object,67,2.23%,No,No,"Feb-2013, Jun-2016, Jun-2016, Jul-2014"
44,collections_12_mths_ex_med,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.03%,No,Yes,"1.0, 1.0, 1.0, 1.0"
46,application_type,object,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,3,0.10%,No,Yes,"0.0, 0.0, 0.0, 0.0"
51,tax_liens,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"

-------------------------------------------------------------------------------------

Chunk 9
Memory Footprint: 4.0978 MB

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,int64,3000,100.00%,No,No,"605439, 606429, 606401, 606324"
1,member_id,float64,3000,100.00%,No,Yes,"776716.0, 777950.0, 777912.0, 777817.0"
2,loan_amnt,float64,239,7.97%,No,Yes,"12000.0, 1200.0, 12000.0, 20000.0"
3,funded_amnt,float64,348,11.60%,No,Yes,"8225.0, 1200.0, 7575.0, 20000.0"
4,funded_amnt_inv,float64,1263,42.10%,No,No,"7983.700527121353, 1200.0, 7467.845225194359, ..."
5,term,object,2,0.07%,No,No,"36 months, 36 months, 36 months, 36 months"
6,int_rate,object,68,2.27%,No,No,"6.54%, 12.98%, 6.91%, 14.09%"
7,installment,float64,1773,59.10%,No,No,"252.24, 40.43, 233.59, 684.43"
8,grade,object,7,0.23%,No,No,"A, C, A, D"
9,sub_grade,object,35,1.17%,No,No,"A4, C3, A5, D1"
10,emp_title,object,2660,88.67%,Yes,No,"EZ Apparel, Abercrombie & Fitch, Quickie Manuf..."
11,emp_length,object,11,0.37%,Yes,No,"1 year, 2 years, 1 year, 8 years"
12,home_ownership,object,3,0.10%,No,No,"RENT, MORTGAGE, RENT, RENT"
13,annual_inc,float64,843,28.10%,No,No,"50000.0, 48000.0, 56000.0, 71004.0"
14,verification_status,object,3,0.10%,No,No,"Verified, Verified, Verified, Verified"
15,issue_d,object,4,0.13%,No,No,"Nov-2010, Oct-2010, Nov-2010, Nov-2010"
16,loan_status,object,4,0.13%,No,No,"Fully Paid, Charged Off, Fully Paid, Fully Paid"
17,pymnt_plan,object,2,0.07%,No,No,"n, n, n, n"
18,purpose,object,14,0.47%,No,No,"other, home_improvement, debt_consolidation, d..."
19,title,object,1881,62.70%,Yes,No,"Credit card debt consolidation, Furnace Loan, ..."
20,zip_code,object,555,18.50%,No,No,"100xx, 430xx, 086xx, 074xx"
21,addr_state,object,43,1.43%,No,No,"NY, OH, NJ, NJ"
22,dti,float64,1698,56.60%,No,No,"2.47, 17.75, 22.88, 23.68"
23,delinq_2yrs,float64,7,0.23%,No,Yes,"0.0, 1.0, 0.0, 0.0"
24,earliest_cr_line,object,374,12.47%,No,No,"Dec-2003, Sep-2000, Nov-1997, Dec-1998"
25,inq_last_6mths,float64,8,0.27%,No,Yes,"1.0, 2.0, 2.0, 2.0"
26,open_acc,float64,30,1.00%,No,Yes,"5.0, 21.0, 11.0, 6.0"
27,pub_rec,float64,3,0.10%,No,Yes,"0.0, 0.0, 0.0, 0.0"
28,revol_bal,float64,2763,92.10%,No,Yes,"5300.0, 6603.0, 14631.0, 20280.0"
29,revol_util,object,958,31.93%,Yes,No,"30.6%, 82.5%, 54.8%, 83.1%"
30,total_acc,float64,62,2.07%,No,Yes,"8.0, 43.0, 25.0, 38.0"
31,initial_list_status,object,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float64,3,0.10%,No,No,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,3,0.10%,No,No,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,3000,100.00%,No,No,"9080.9979521352, 120.99, 8409.1225259244, 2323..."
35,total_pymnt_inv,float64,2993,99.77%,No,No,"8804.99, 120.99, 8279.62, 23230.29"
36,total_rec_prncp,float64,791,26.37%,No,No,"8225.0, 83.04, 7575.0, 20000.0"
37,total_rec_int,float64,2945,98.17%,No,No,"856.0, 37.95, 834.12, 3230.29"
38,total_rec_late_fee,float64,144,4.80%,No,No,"0.0, 0.0, 0.0, 0.0"
39,recoveries,float64,336,11.20%,No,No,"0.0, 0.0, 0.0, 0.0"
40,collection_recovery_fee,float64,284,9.47%,No,No,"0.0, 0.0, 0.0, 0.0"
41,last_pymnt_d,object,66,2.20%,Yes,No,"Nov-2013, Feb-2011, Nov-2013, Apr-2012"
42,last_pymnt_amnt,float64,2946,98.20%,No,No,"281.87, 40.43, 239.96, 12309.93"
43,last_credit_pull_d,object,70,2.33%,Yes,No,"Nov-2013, Jun-2016, Jun-2016, Jun-2016"
44,collections_12_mths_ex_med,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.03%,No,Yes,"1.0, 1.0, 1.0, 1.0"
46,application_type,object,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,2,0.07%,No,Yes,"0.0, 0.0, 0.0, 0.0"
51,tax_liens,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"

-------------------------------------------------------------------------------------

Chunk 10
Memory Footprint: 4.0977 MB

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,int64,3000,100.00%,No,No,"560923, 561083, 561027, 560993"
1,member_id,float64,3000,100.00%,No,Yes,"721913.0, 722112.0, 722048.0, 722008.0"
2,loan_amnt,float64,212,7.07%,No,Yes,"6000.0, 6000.0, 10000.0, 10000.0"
3,funded_amnt,float64,413,13.77%,No,Yes,"6000.0, 6000.0, 10000.0, 10000.0"
4,funded_amnt_inv,float64,1433,47.77%,No,No,"6000.0, 5498.26, 9975.0, 9500.0"
5,term,object,2,0.07%,No,No,"36 months, 36 months, 60 months, 36 months"
6,int_rate,object,50,1.67%,No,No,"13.61%, 11.86%, 15.95%, 7.88%"
7,installment,float64,1784,59.47%,No,No,"203.94, 198.89, 242.92, 312.82"
8,grade,object,7,0.23%,No,No,"C, B, D, A"
9,sub_grade,object,34,1.13%,No,No,"C2, B5, D4, A5"
10,emp_title,object,2654,88.47%,Yes,No,"bricco, Andrews Federal Credit Union, ABF Frei..."
11,emp_length,object,11,0.37%,Yes,No,"6 years, 2 years, 10+ years, 3 years"
12,home_ownership,object,3,0.10%,No,No,"RENT, RENT, RENT, MORTGAGE"
13,annual_inc,float64,850,28.33%,No,No,"24996.0, 36000.0, 53000.0, 72000.0"
14,verification_status,object,3,0.10%,No,No,"Not Verified, Source Verified, Not Verified, N..."
15,issue_d,object,4,0.13%,No,No,"Aug-2010, Aug-2010, Aug-2010, Aug-2010"
16,loan_status,object,2,0.07%,No,No,"Fully Paid, Fully Paid, Fully Paid, Fully Paid"
17,pymnt_plan,object,1,0.03%,No,No,"n, n, n, n"
18,purpose,object,14,0.47%,No,No,"other, debt_consolidation, debt_consolidation,..."
19,title,object,2139,71.30%,Yes,No,"personal, Debt Consolidation, britschool, Big ..."
20,zip_code,object,524,17.47%,No,No,"061xx, 207xx, 103xx, 494xx"
21,addr_state,object,42,1.40%,No,No,"CT, MD, NY, MI"
22,dti,float64,1715,57.17%,No,No,"10.23, 16.87, 15.8, 2.12"
23,delinq_2yrs,float64,7,0.23%,No,Yes,"0.0, 0.0, 0.0, 0.0"
24,earliest_cr_line,object,367,12.23%,No,No,"Jan-2006, May-2006, Jun-1999, Sep-1998"
25,inq_last_6mths,float64,9,0.30%,No,Yes,"2.0, 0.0, 2.0, 0.0"
26,open_acc,float64,28,0.93%,No,Yes,"13.0, 7.0, 5.0, 5.0"
27,pub_rec,float64,4,0.13%,No,Yes,"0.0, 0.0, 0.0, 0.0"
28,revol_bal,float64,2781,92.70%,No,Yes,"5202.0, 3803.0, 7659.0, 0.0"
29,revol_util,object,942,31.40%,Yes,No,"50.5%, 79.2%, 69.6%, 0%"
30,total_acc,float64,66,2.20%,No,Yes,"19.0, 12.0, 12.0, 21.0"
31,initial_list_status,object,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,2998,99.93%,No,No,"7341.918557436399, 6334.8310496491, 14574.7440..."
35,total_pymnt_inv,float64,2988,99.60%,No,No,"7341.92, 5804.47, 14538.31, 9776.25"
36,total_rec_prncp,float64,826,27.53%,No,No,"6000.0, 6000.0, 10000.0, 10000.0"
37,total_rec_int,float64,2945,98.17%,No,No,"1341.92, 334.83, 4574.74, 290.77"
38,total_rec_late_fee,float64,160,5.33%,No,No,"0.0, 0.0, 0.0, 0.0"
39,recoveries,float64,311,10.37%,No,No,"0.0, 0.0, 0.0, 0.0"
40,collection_recovery_fee,float64,262,8.73%,No,No,"0.0, 0.0, 0.0, 0.0"
41,last_pymnt_d,object,65,2.17%,Yes,No,"Aug-2013, Feb-2011, Aug-2015, Feb-2011"
42,last_pymnt_amnt,float64,2945,98.17%,No,No,"230.57, 5345.19, 265.66, 2729.53"
43,last_credit_pull_d,object,72,2.40%,No,No,"Aug-2013, Aug-2014, Nov-2015, Oct-2015"
44,collections_12_mths_ex_med,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.03%,No,Yes,"1.0, 1.0, 1.0, 1.0"
46,application_type,object,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,2,0.07%,No,Yes,"0.0, 0.0, 0.0, 0.0"
51,tax_liens,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"

-------------------------------------------------------------------------------------

Chunk 11
Memory Footprint: 4.1107 MB

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,int64,3000,100.00%,No,No,"516349, 516322, 516336, 516327"
1,member_id,float64,3000,100.00%,No,Yes,"667371.0, 667341.0, 667356.0, 667340.0"
2,loan_amnt,float64,222,7.40%,No,Yes,"14400.0, 21500.0, 5000.0, 8000.0"
3,funded_amnt,float64,228,7.60%,No,Yes,"14400.0, 21500.0, 5000.0, 8000.0"
4,funded_amnt_inv,float64,1097,36.57%,No,No,"14400.0, 20775.0, 5000.0, 7950.0"
5,term,object,2,0.07%,No,No,"60 months, 36 months, 36 months, 36 months"
6,int_rate,object,60,2.00%,No,No,"7.88%, 10.62%, 11.36%, 11.36%"
7,installment,float64,1247,41.57%,No,No,"291.16, 700.02, 164.55, 263.28"
8,grade,object,7,0.23%,No,No,"A, B, B, B"
9,sub_grade,object,34,1.13%,No,No,"A5, B3, B5, B5"
10,emp_title,object,2644,88.13%,Yes,No,"City of Taylorville, Kemper Insurance Company,..."
11,emp_length,object,11,0.37%,Yes,No,"10+ years, 10+ years, 10+ years, 3 years"
12,home_ownership,object,4,0.13%,No,No,"MORTGAGE, RENT, MORTGAGE, MORTGAGE"
13,annual_inc,float64,840,28.00%,No,No,"54000.0, 132000.0, 43200.0, 54036.0"
14,verification_status,object,3,0.10%,No,No,"Not Verified, Verified, Not Verified, Verified"
15,issue_d,object,5,0.17%,No,No,"May-2010, May-2010, May-2010, May-2010"
16,loan_status,object,2,0.07%,No,No,"Fully Paid, Fully Paid, Fully Paid, Fully Paid"
17,pymnt_plan,object,1,0.03%,No,No,"n, n, n, n"
18,purpose,object,14,0.47%,No,No,"credit_card, debt_consolidation, credit_card, ..."
19,title,object,2425,80.83%,Yes,No,"Lower Interest & Pay off faster single c, Jim'..."
20,zip_code,object,527,17.57%,No,No,"625xx, 600xx, 335xx, 596xx"
21,addr_state,object,41,1.37%,No,No,"IL, IL, FL, MT"
22,dti,float64,1708,56.93%,No,No,"17.47, 11.7, 20.39, 23.1"
23,delinq_2yrs,float64,5,0.17%,No,Yes,"0.0, 0.0, 0.0, 0.0"
24,earliest_cr_line,object,363,12.10%,No,No,"Jul-1993, Sep-1996, Nov-1993, Jan-1988"
25,inq_last_6mths,float64,8,0.27%,No,Yes,"1.0, 2.0, 1.0, 0.0"
26,open_acc,float64,30,1.00%,No,Yes,"7.0, 9.0, 8.0, 9.0"
27,pub_rec,float64,5,0.17%,No,Yes,"0.0, 0.0, 1.0, 0.0"
28,revol_bal,float64,2735,91.17%,No,Yes,"11832.0, 0.0, 11407.0, 255.0"
29,revol_util,object,948,31.60%,Yes,No,"56.3%, 0%, 70.9%, 45.6%"
30,total_acc,float64,68,2.27%,No,Yes,"34.0, 21.0, 19.0, 39.0"
31,initial_list_status,object,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,3000,100.00%,No,No,"17469.149996316297, 22893.651181329904, 5492.4..."
35,total_pymnt_inv,float64,2986,99.53%,No,No,"17469.15, 22121.65, 5492.41, 9419.38"
36,total_rec_prncp,float64,551,18.37%,No,No,"14400.0, 21500.0, 5000.0, 8000.0"
37,total_rec_int,float64,2949,98.30%,No,No,"3069.15, 1393.65, 492.41, 1478.62"
38,total_rec_late_fee,float64,187,6.23%,No,No,"0.0, 0.0, 0.0, 0.0"
39,recoveries,float64,225,7.50%,No,No,"0.0, 0.0, 0.0, 0.0"
40,collection_recovery_fee,float64,208,6.93%,No,No,"0.0, 0.0, 0.0, 0.0"
41,last_pymnt_d,object,53,1.77%,Yes,No,"Jun-2015, Feb-2011, Jun-2011, Jun-2013"
42,last_pymnt_amnt,float64,2937,97.90%,No,No,"308.67, 18001.15, 3686.55, 276.51"
43,last_credit_pull_d,object,77,2.57%,No,No,"Sep-2015, Jun-2016, Jun-2011, Jun-2016"
44,collections_12_mths_ex_med,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.03%,No,Yes,"1.0, 1.0, 1.0, 1.0"
46,application_type,object,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,3,0.10%,No,Yes,"0.0, 0.0, 1.0, 0.0"
51,tax_liens,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"

-------------------------------------------------------------------------------------

Chunk 12
Memory Footprint: 4.1093 MB

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,int64,3000,100.00%,No,No,"475784, 474235, 475900, 475648"
1,member_id,float64,3000,100.00%,No,Yes,"602478.0, 599846.0, 602656.0, 602213.0"
2,loan_amnt,float64,257,8.57%,No,Yes,"15000.0, 2800.0, 3000.0, 5000.0"
3,funded_amnt,float64,260,8.67%,No,Yes,"15000.0, 2800.0, 3000.0, 5000.0"
4,funded_amnt_inv,float64,1539,51.30%,No,No,"14889.352048998177, 2800.0, 3000.0, 5000.0"
5,term,object,1,0.03%,No,No,"36 months, 36 months, 36 months, 36 months"
6,int_rate,object,65,2.17%,No,No,"12.18%, 16.00%, 11.83%, 12.18%"
7,installment,float64,1282,42.73%,No,No,"499.5, 98.45, 99.41, 166.5"
8,grade,object,7,0.23%,No,No,"B, D, B, B"
9,sub_grade,object,35,1.17%,No,No,"B4, D5, B3, B4"
10,emp_title,object,2554,85.13%,Yes,No,"General Casualty Insurance, Governor's Office ..."
11,emp_length,object,11,0.37%,No,No,"4 years, 2 years, 3 years, 6 years"
12,home_ownership,object,4,0.13%,No,No,"RENT, RENT, RENT, RENT"
13,annual_inc,float64,881,29.37%,No,No,"45400.0, 42000.0, 34500.0, 14573.0"
14,verification_status,object,3,0.10%,No,No,"Not Verified, Not Verified, Not Verified, Not ..."
15,issue_d,object,7,0.23%,No,No,"Jan-2010, Jan-2010, Jan-2010, Jan-2010"
16,loan_status,object,2,0.07%,No,No,"Fully Paid, Fully Paid, Fully Paid, Fully Paid"
17,pymnt_plan,object,1,0.03%,No,No,"n, n, n, n"
18,purpose,object,14,0.47%,No,No,"debt_consolidation, wedding, house, other"
19,title,object,2335,77.83%,No,No,"loan, For my wedding, Helping Dad with House, ..."
20,zip_code,object,538,17.93%,No,No,"535xx, 300xx, 017xx, 243xx"
21,addr_state,object,42,1.40%,No,No,"WI, GA, MA, VA"
22,dti,float64,1682,56.07%,No,No,"1.5, 22.31, 20.94, 10.95"
23,delinq_2yrs,float64,6,0.20%,No,Yes,"0.0, 0.0, 0.0, 0.0"
24,earliest_cr_line,object,373,12.43%,No,No,"Jun-1996, Oct-2001, Jul-2004, Nov-2003"
25,inq_last_6mths,float64,9,0.30%,No,Yes,"1.0, 0.0, 3.0, 0.0"
26,open_acc,float64,33,1.10%,No,Yes,"8.0, 3.0, 9.0, 7.0"
27,pub_rec,float64,4,0.13%,No,Yes,"0.0, 0.0, 0.0, 0.0"
28,revol_bal,float64,2739,91.30%,No,Yes,"17516.0, 14850.0, 5626.0, 3753.0"
29,revol_util,object,950,31.67%,Yes,No,"84.6%, 99%, 30.1%, 51.4%"
30,total_acc,float64,64,2.13%,No,Yes,"18.0, 8.0, 16.0, 10.0"
31,initial_list_status,object,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,2988,99.60%,No,No,"17661.642090498503, 3105.7473669691, 3516.4204..."
35,total_pymnt_inv,float64,2969,98.97%,No,No,"17529.79, 3105.75, 3516.42, 5723.61"
36,total_rec_prncp,float64,662,22.07%,No,No,"15000.0, 2800.0, 3000.0, 5000.0"
37,total_rec_int,float64,2834,94.47%,No,No,"2661.64, 305.75, 516.42, 723.61"
38,total_rec_late_fee,float64,217,7.23%,No,No,"0.0, 0.0, 0.0, 0.0"
39,recoveries,float64,274,9.13%,No,No,"0.0, 0.0, 0.0, 0.0"
40,collection_recovery_fee,float64,237,7.90%,No,No,"0.0, 0.0, 0.0, 0.0"
41,last_pymnt_d,object,50,1.67%,Yes,No,"Mar-2012, Oct-2010, Mar-2012, Jul-2011"
42,last_pymnt_amnt,float64,2923,97.43%,No,No,"5688.39, 2320.25, 1139.23, 2897.23"
43,last_credit_pull_d,object,83,2.77%,No,No,"Jun-2016, Nov-2010, May-2016, Jul-2011"
44,collections_12_mths_ex_med,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.03%,No,Yes,"1.0, 1.0, 1.0, 1.0"
46,application_type,object,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,2,0.07%,Yes,No,"0.0, 0.0, 0.0, 0.0"
51,tax_liens,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"

-------------------------------------------------------------------------------------

Chunk 13
Memory Footprint: 4.1152 MB

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,int64,3000,100.00%,No,No,"412050, 426918, 426414, 426858"
1,member_id,float64,3000,100.00%,No,Yes,"464682.0, 499814.0, 503374.0, 504130.0"
2,loan_amnt,float64,260,8.67%,No,Yes,"15600.0, 16000.0, 5000.0, 10000.0"
3,funded_amnt,float64,329,10.97%,No,Yes,"15600.0, 16000.0, 5000.0, 10000.0"
4,funded_amnt_inv,float64,2145,71.50%,No,No,"11808.688749289551, 15850.0, 4950.0, 9950.0"
5,term,object,1,0.03%,No,No,"36 months, 36 months, 36 months, 36 months"
6,int_rate,object,107,3.57%,No,No,"12.84%, 11.89%, 8.00%, 11.89%"
7,installment,float64,1625,54.17%,No,No,"524.44, 530.63, 156.69, 331.64"
8,grade,object,7,0.23%,No,No,"C, B, A, B"
9,sub_grade,object,35,1.17%,No,No,"C2, B4, A3, B4"
10,emp_title,object,2598,86.60%,Yes,No,"Associates in Family Practice, Camden County P..."
11,emp_length,object,11,0.37%,No,No,"3 years, 10+ years, 3 years, 10+ years"
12,home_ownership,object,4,0.13%,No,No,"RENT, RENT, MORTGAGE, RENT"
13,annual_inc,float64,875,29.17%,No,No,"68324.0, 94000.0, 28000.0, 90000.0"
14,verification_status,object,3,0.10%,No,No,"Verified, Verified, Not Verified, Verified"
15,issue_d,object,17,0.57%,No,No,"Jul-2009, Jul-2009, Jul-2009, Jul-2009"
16,loan_status,object,2,0.07%,No,No,"Fully Paid, Fully Paid, Fully Paid, Fully Paid"
17,pymnt_plan,object,1,0.03%,No,No,"n, n, n, n"
18,purpose,object,14,0.47%,No,No,"credit_card, debt_consolidation, major_purchas..."
19,title,object,2297,76.57%,Yes,No,"Refinancing Credit Card., Debt Consolidation, ..."
20,zip_code,object,574,19.13%,No,No,"333xx, 080xx, 329xx, 191xx"
21,addr_state,object,47,1.57%,No,No,"FL, NJ, FL, PA"
22,dti,float64,1693,56.43%,No,No,"6.73, 13.93, 2.36, 13.95"
23,delinq_2yrs,float64,6,0.20%,No,Yes,"0.0, 0.0, 0.0, 0.0"
24,earliest_cr_line,object,366,12.20%,No,No,"Jul-2003, Feb-1990, Jul-2003, Nov-1990"
25,inq_last_6mths,float64,9,0.30%,No,Yes,"0.0, 1.0, 1.0, 0.0"
26,open_acc,float64,31,1.03%,No,Yes,"7.0, 15.0, 6.0, 7.0"
27,pub_rec,float64,4,0.13%,No,Yes,"0.0, 0.0, 0.0, 1.0"
28,revol_bal,float64,2789,92.97%,No,Yes,"15712.0, 9867.0, 2583.0, 32678.0"
29,revol_util,object,929,30.97%,Yes,No,"84.3%, 24.1%, 31.5%, 75.8%"
30,total_acc,float64,62,2.07%,No,Yes,"16.0, 22.0, 7.0, 18.0"
31,initial_list_status,object,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,2993,99.77%,No,No,"18846.9301731956, 19102.378598099294, 5270.795..."
35,total_pymnt_inv,float64,2825,94.17%,No,No,"13807.84, 18923.29, 5218.09, 11879.32"
36,total_rec_prncp,float64,843,28.10%,No,No,"15599.99, 16000.0, 5000.0, 10000.0"
37,total_rec_int,float64,2732,91.07%,No,No,"3246.94, 3102.38, 270.8, 1939.02"
38,total_rec_late_fee,float64,229,7.63%,No,No,"0.0, 0.0, 0.0, 0.0"
39,recoveries,float64,237,7.90%,No,No,"0.0, 0.0, 0.0, 0.0"
40,collection_recovery_fee,float64,215,7.17%,No,No,"0.0, 0.0, 0.0, 0.0"
41,last_pymnt_d,object,59,1.97%,Yes,No,"May-2012, Aug-2012, May-2010, Aug-2012"
42,last_pymnt_amnt,float64,2939,97.97%,No,No,"2068.74, 585.09, 4176.92, 376.55"
43,last_credit_pull_d,object,97,3.23%,No,No,"May-2014, Jun-2016, Feb-2016, Jul-2012"
44,collections_12_mths_ex_med,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.03%,No,Yes,"1.0, 1.0, 1.0, 1.0"
46,application_type,object,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,2,0.07%,Yes,No,"0.0, 0.0, 0.0, 1.0"
51,tax_liens,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"

-------------------------------------------------------------------------------------

Chunk 14
Memory Footprint: 4.3267 MB

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,object,3000,100.00%,No,No,"298963, 298946, 298649, 297158"
1,member_id,float64,2999,99.97%,Yes,No,"298960.0, 298943.0, 298568.0, 297155.0"
2,loan_amnt,float64,315,10.50%,Yes,No,"18500.0, 6000.0, 10000.0, 10000.0"
3,funded_amnt,float64,361,12.03%,Yes,No,"18500.0, 6000.0, 10000.0, 10000.0"
4,funded_amnt_inv,float64,1655,55.17%,Yes,No,"7082.589999999998, 4600.0, 9003.43, 8604.26"
5,term,object,2,0.07%,Yes,No,"36 months, 36 months, 36 months, 36 months"
6,int_rate,object,262,8.73%,Yes,No,"10.71%, 12.92%, 11.66%, 11.34%"
7,installment,float64,2400,80.00%,Yes,No,"603.13, 201.94, 330.53, 329.0"
8,grade,object,7,0.23%,Yes,No,"B, D, C, C"
9,sub_grade,object,35,1.17%,Yes,No,"B5, D2, C3, C2"
10,emp_title,object,2605,86.83%,Yes,No,"Navigation Solutions, St Lukes Medical Center,..."
11,emp_length,object,11,0.37%,Yes,No,"4 years, 1 year, < 1 year, < 1 year"
12,home_ownership,object,5,0.17%,Yes,No,"RENT, MORTGAGE, RENT, MORTGAGE"
13,annual_inc,float64,832,27.73%,Yes,No,"34300.0, 40800.0, 120000.0, 50000.0"
14,verification_status,object,3,0.10%,Yes,No,"Not Verified, Not Verified, Not Verified, Not ..."
15,issue_d,object,43,1.43%,Yes,No,"Mar-2008, Mar-2008, Mar-2008, Mar-2008"
16,loan_status,object,4,0.13%,Yes,No,"Fully Paid, Fully Paid, Fully Paid, Fully Paid"
17,pymnt_plan,object,1,0.03%,Yes,No,"n, n, n, n"
18,purpose,object,14,0.47%,Yes,No,"debt_consolidation, debt_consolidation, credit..."
19,title,object,2287,76.23%,Yes,No,"Personal Loan, debt consolidation, CC Debt - R..."
20,zip_code,object,609,20.30%,Yes,No,"220xx, 837xx, 631xx, 770xx"
21,addr_state,object,50,1.67%,Yes,No,"VA, ID, MO, TX"
22,dti,float64,1761,58.70%,Yes,No,"13.33, 15.32, 8.13, 12.05"
23,delinq_2yrs,float64,9,0.30%,Yes,No,"0.0, 2.0, 0.0, 0.0"
24,earliest_cr_line,object,381,12.70%,Yes,No,"Sep-1995, Oct-2000, Oct-1999, Oct-2003"
25,inq_last_6mths,float64,20,0.67%,Yes,No,"0.0, 2.0, 0.0, 0.0"
26,open_acc,float64,39,1.30%,Yes,No,"7.0, 11.0, 6.0, 9.0"
27,pub_rec,float64,5,0.17%,Yes,No,"0.0, 0.0, 0.0, 0.0"
28,revol_bal,float64,2763,92.10%,Yes,No,"18179.0, 7091.0, 59145.0, 13744.0"
29,revol_util,object,954,31.80%,Yes,No,"34.4%, 47.3%, 81.1%, 62.2%"
30,total_acc,float64,69,2.30%,Yes,No,"30.0, 13.0, 9.0, 10.0"
31,initial_list_status,object,1,0.03%,Yes,No,"f, f, f, f"
32,out_prncp,float64,1,0.03%,Yes,No,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,1,0.03%,Yes,No,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,2993,99.77%,Yes,No,"21712.7114301377, 6939.5988811354, 11898.72411..."
35,total_pymnt_inv,float64,2866,95.53%,Yes,No,"8033.43, 5320.36, 10689.07, 10166.11"
36,total_rec_prncp,float64,1084,36.13%,Yes,No,"18500.0, 6000.0, 10000.0, 10000.0"
37,total_rec_int,float64,2937,97.90%,Yes,No,"3212.72, 939.6, 1898.72, 1844.01"
38,total_rec_late_fee,float64,313,10.43%,Yes,No,"0.0, 0.0, 0.0, 0.0"
39,recoveries,float64,470,15.67%,Yes,No,"0.0, 0.0, 0.0, 0.0"
40,collection_recovery_fee,float64,396,13.20%,Yes,No,"0.0, 0.0, 0.0, 0.0"
41,last_pymnt_d,object,96,3.20%,Yes,No,"Apr-2011, Dec-2009, Apr-2011, Apr-2011"
42,last_pymnt_amnt,float64,2917,97.23%,Yes,No,"620.45, 2309.4, 371.96, 347.16"
43,last_credit_pull_d,object,105,3.50%,Yes,No,"Mar-2011, Dec-2009, Sep-2014, Mar-2011"
44,collections_12_mths_ex_med,float64,1,0.03%,Yes,No,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.03%,Yes,No,"1.0, 1.0, 1.0, 1.0"
46,application_type,object,1,0.03%,Yes,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,1,0.03%,Yes,No,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.03%,Yes,No,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,1,0.03%,Yes,No,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,3,0.10%,Yes,No,"0.0, 0.0, 0.0, 0.0"
51,tax_liens,float64,1,0.03%,Yes,No,"0.0, 0.0, 0.0, 0.0"

-------------------------------------------------------------------------------------

Chunk 15
Memory Footprint: 0.7794 MB

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,object,538,100.00%,No,No,"247286, 246996, 246720, 246535"
1,member_id,float64,536,99.63%,Yes,No,"247257.0, 244258.0, 246706.0, 246427.0"
2,loan_amnt,float64,149,27.70%,Yes,No,"6000.0, 17250.0, 13000.0, 12000.0"
3,funded_amnt,float64,150,27.88%,Yes,No,"6000.0, 17250.0, 13000.0, 12000.0"
4,funded_amnt_inv,float64,354,65.80%,Yes,No,"4201.94, 12150.005316292236, 7700.0, 5650.0"
5,term,object,1,0.19%,Yes,No,"36 months, 36 months, 36 months, 36 months"
6,int_rate,object,86,15.99%,Yes,No,"11.34%, 17.66%, 15.13%, 18.29%"
7,installment,float64,469,87.17%,Yes,No,"197.4, 620.7, 451.48, 435.58"
8,grade,object,7,1.30%,Yes,No,"C, G, E, G"
9,sub_grade,object,35,6.51%,Yes,No,"C2, G2, E4, G4"
10,emp_title,object,477,88.66%,Yes,No,"Best Buy, CVS PHARMACY, General Motors, usa me..."
11,emp_length,object,11,2.04%,Yes,No,"3 years, 2 years, 7 years, 6 years"
12,home_ownership,object,4,0.74%,Yes,No,"RENT, OWN, RENT, RENT"
13,annual_inc,float64,224,41.64%,Yes,No,"32000.0, 62000.0, 78000.0, 62000.0"
14,verification_status,object,1,0.19%,Yes,No,"Not Verified, Not Verified, Not Verified, Not ..."
15,issue_d,object,9,1.67%,Yes,No,"Feb-2008, Feb-2008, Feb-2008, Feb-2008"
16,loan_status,object,2,0.37%,Yes,No,Does not meet the credit policy. Status:Fully ...
17,pymnt_plan,object,1,0.19%,Yes,No,"n, n, n, n"
18,purpose,object,13,2.42%,Yes,No,"debt_consolidation, debt_consolidation, debt_c..."
19,title,object,462,85.87%,Yes,No,"Paying off Bills, School expenses from residen..."
20,zip_code,object,267,49.63%,Yes,No,"326xx, 787xx, 480xx, 366xx"
21,addr_state,object,42,7.81%,Yes,No,"FL, TX, MI, AL"
22,dti,float64,451,83.83%,Yes,No,"21.9, 20.44, 29.28, 25.26"
23,delinq_2yrs,float64,10,1.86%,Yes,No,"0.0, 0.0, 0.0, 0.0"
24,earliest_cr_line,object,218,40.52%,Yes,No,"Jul-2000, Mar-1989, Dec-1998, Jul-1995"
25,inq_last_6mths,float64,25,4.65%,Yes,No,"0.0, 7.0, 3.0, 3.0"
26,open_acc,float64,32,5.95%,Yes,No,"5.0, 16.0, 6.0, 14.0"
27,pub_rec,float64,4,0.74%,Yes,No,"0.0, 0.0, 0.0, 0.0"
28,revol_bal,float64,458,85.13%,Yes,No,"7152.0, 28776.0, 61057.0, 13560.0"
29,revol_util,object,379,70.45%,Yes,No,"100.7%, 51.9%, 80.7%, 57.2%"
30,total_acc,float64,54,10.04%,Yes,No,"12.0, 19.0, 17.0, 41.0"
31,initial_list_status,object,1,0.19%,Yes,No,"f, f, f, f"
32,out_prncp,float64,1,0.19%,Yes,No,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,1,0.19%,Yes,No,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,536,99.63%,Yes,No,"7106.392519058899, 4344.89, 16253.1584188383, ..."
35,total_pymnt_inv,float64,528,98.14%,Yes,No,"4960.0, 3058.87, 9626.87, 7383.0"
36,total_rec_prncp,float64,303,56.32%,Yes,No,"6000.0, 2278.94, 13000.0, 12000.0"
37,total_rec_int,float64,532,98.88%,Yes,No,"1106.4, 2065.95, 3253.16, 3680.71"
38,total_rec_late_fee,float64,76,14.13%,Yes,No,"0.0, 0.0, 0.0, 0.0"
39,recoveries,float64,103,19.14%,Yes,No,"0.0, 0.0, 0.0, 0.0"
40,collection_recovery_fee,float64,99,18.40%,Yes,No,"0.0, 0.0, 0.0, 0.0"
41,last_pymnt_d,object,45,8.36%,Yes,No,"Feb-2011, Nov-2008, Feb-2011, Feb-2011"
42,last_pymnt_amnt,float64,522,97.03%,Yes,No,"207.82, 621.01, 470.66, 450.84"
43,last_credit_pull_d,object,89,16.54%,Yes,No,"Jun-2016, Jun-2016, Jun-2016, Jun-2011"
44,collections_12_mths_ex_med,float64,1,0.19%,Yes,No,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.19%,Yes,No,"1.0, 1.0, 1.0, 1.0"
46,application_type,object,1,0.19%,Yes,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,2,0.37%,Yes,No,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.19%,Yes,No,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,3,0.56%,Yes,No,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,2,0.37%,Yes,No,"nan, nan, nan, nan"
51,tax_liens,float64,2,0.37%,Yes,No,"0.0, 0.0, 0.0, 0.0"

-------------------------------------------------------------------------------------

[Back to Table of Contents](#toc)

We now have a comprehensive summary of each chunk. Next, we will calculate the total memory consumption of the entire dataset by aggregating the memory usage of all combined chunks.

In [7]:
print(f"Total Memory: {total_memory}")

Total Memory: 58.43076229095459

### Chunk Data Type Consistency
<a id="chunk-consistency"></a>
Next, we will differentiate between our string (object) columns and our numeric columns.

In [8]:
chunk_iter = pd.read_csv('loans_2007.csv', chunksize=3000)

summaries = []

for chunk in chunk_iter:
    summary, footprint = profile_chunk(chunk)
    summaries.append(summary)

In [9]:
# baseline from the first chunk
first_chunk = summaries[0]

numeric_cols = first_chunk[first_chunk['Dtype'].astype(str).str.contains('int|float')]['Column'].tolist()
string_cols = first_chunk[first_chunk['Dtype'].astype(str).str.contains('object')]['Column'].tolist()

print(f"Numeric Columns ({len(numeric_cols)}): {numeric_cols}\n")
print(f"String Columns ({len(string_cols)}): {string_cols}")

Numeric Columns (31): ['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'installment', 'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'total_acc', 'out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee', 'recoveries', 'collection_recovery_fee', 'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code', 'acc_now_delinq', 'chargeoff_within_12_mths', 'delinq_amnt', 'pub_rec_bankruptcies', 'tax_liens']

String Columns (21): ['term', 'int_rate', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'verification_status', 'issue_d', 'loan_status', 'pymnt_plan', 'purpose', 'title', 'zip_code', 'addr_state', 'earliest_cr_line', 'revol_util', 'initial_list_status', 'last_pymnt_d', 'last_credit_pull_d', 'application_type']

Now that we have identified the column types, we need to verify consistency across the dataset. We will check if the data types remain uniform across all chunks or if any columns were assigned different types due to varying data in specific chunks.

In [10]:
dtype_changes = []

# Column/dtype mapping from the first chunk to compare against
baseline_dtypes = summaries[0].set_index('Column')['Dtype']

for i, report in enumerate(summaries):
    current_dtypes = report.set_index('Column')['Dtype']
    
    # Check if any dtypes in the current chunk differ from our baseline
    inconsistent = current_dtypes[current_dtypes != baseline_dtypes]
    
    if not inconsistent.empty:
        for col, dtype in inconsistent.items():
            dtype_changes.append({
                "Chunk": i + 1,
                "Column": col,
                "Original_Dtype": baseline_dtypes[col],
                "New_Dtype": dtype
            })

if not dtype_changes:
    print("Consistency Check: PASS. All columns have consistent types across all 15 chunks.")
else:
    print("Consistency Check: FAIL. Found the following type shifts:")
    display(pd.DataFrame(dtype_changes))

Consistency Check: FAIL. Found the following type shifts:

   Chunk Column Original_Dtype New_Dtype
0     14     id          int64    object
1     15     id          int64    object

Our analysis shows that the data contains 31 numeric columns and 21 string columns. We discovered that in chunks 14 and 15, the `id` column was assigned as an object/string type, whereas previous chunks identified it as an integer. Since this column will not be used for calculations or modeling, we will leave it as is for now.

Let's begin optimizing our string (object) columns. Our goal is to convert these to more efficient types, such as `category`, `float`, or `datetime`. We will apply the following logic:

* **Object columns** with less than 50% unique values will be converted to the `category` type.
* **Object columns** containing numeric data will be converted to `float`.

The code below inspects the object columns from the first chunk to identify specific candidates for conversion.

[Back to Table of Contents](#toc)

### Column Data Type Conversions
<a id="column-conversions"></a>

In [11]:
first_chunk[first_chunk['Dtype'] == 'object']

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
5,term,object,2,0.07%,No,No,"36 months, 60 months, 36 months, 36 months"
6,int_rate,object,36,1.20%,No,No,"10.65%, 15.27%, 15.96%, 13.49%"
8,grade,object,7,0.23%,No,No,"B, C, C, C"
9,sub_grade,object,35,1.17%,No,No,"B2, C4, C5, C1"
10,emp_title,object,2653,88.43%,Yes,No,"nan, Ryder, nan, AIR RESOURCES BOARD"
11,emp_length,object,11,0.37%,Yes,No,"10+ years, < 1 year, 10+ years, 10+ years"
12,home_ownership,object,3,0.10%,No,No,"RENT, RENT, RENT, RENT"
14,verification_status,object,3,0.10%,No,No,"Verified, Source Verified, Not Verified, Sourc..."
15,issue_d,object,2,0.07%,No,No,"Dec-2011, Dec-2011, Dec-2011, Dec-2011"
16,loan_status,object,6,0.20%,No,No,"Fully Paid, Charged Off, Fully Paid, Fully Paid"
17,pymnt_plan,object,1,0.03%,No,No,"n, n, n, n"
18,purpose,object,13,0.43%,No,No,"credit_card, car, small_business, other"
19,title,object,1406,46.87%,No,No,"Computer, bike, real estate business, personel"
20,zip_code,object,568,18.93%,No,No,"860xx, 309xx, 606xx, 917xx"
21,addr_state,object,43,1.43%,No,No,"AZ, GA, IL, CA"
24,earliest_cr_line,object,366,12.20%,No,No,"Jan-1985, Apr-1999, Nov-2001, Feb-1996"
29,revol_util,object,884,29.47%,No,No,"83.7%, 9.4%, 98.5%, 21%"
31,initial_list_status,object,1,0.03%,No,No,"f, f, f, f"
41,last_pymnt_d,object,54,1.80%,Yes,No,"Jan-2015, Apr-2013, Jun-2014, Jan-2015"
43,last_credit_pull_d,object,55,1.83%,No,No,"Jun-2016, Sep-2013, Jun-2016, Apr-2016"
46,application_type,object,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"

Based on our inspection, we have decided to implement the following data type changes:

* `id`: **`object`**
* `term`, `grade`, `sub_grade`, `emp_length`, `home_ownership`, `verification_status`, `loan_status`, `pymnt_plan`, `purpose`, `title`, `zip_code`, `addr_state`, `initial_list_status`, `application_type`: **`category`**
* `int_rate`, `revol_util`: **`float`**
* `issue_d`, `earliest_cr_line`, `last_pymnt_d`, `last_credit_pull_d`: **`datetime`**

In [12]:
improved_col_dtypes = {
    'id': 'object', 'term': 'category', 'grade': 'category', 'sub_grade': 'category',
    'emp_length': 'category', 'home_ownership': 'category',
    'verification_status': 'category', 'loan_status': 'category', 
    'pymnt_plan': 'category', 'purpose': 'category', 'title': 'category', 
    'zip_code': 'category', 'addr_state': 'category', 
    'initial_list_status': 'category', 'application_type': 'category'
}

In [13]:
chunk_iter = pd.read_csv(
    'loans_2007.csv', 
    chunksize=3000, 
    dtype=improved_col_dtypes, 
    parse_dates=["issue_d", "earliest_cr_line", "last_pymnt_d", "last_credit_pull_d"],
    date_format='%b-%Y'
)

summaries = []
total_memory = 0

for chunk in chunk_iter:
    summary, footprint = profile_chunk(chunk)
    summaries.append(summary)
    total_memory += footprint

print(f"Total Memory Across All Chunks: {total_memory:.2f} MB")
print("\n")
print("First Chunk:")
display(summaries[0])

Total Memory Across All Chunks: 24.31 MB


First Chunk:

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,object,3000,100.00%,No,No,"1077501, 1077430, 1077175, 1076863"
1,member_id,float64,3000,100.00%,No,Yes,"1296599.0, 1314167.0, 1313524.0, 1277178.0"
2,loan_amnt,float64,390,13.00%,No,Yes,"5000.0, 2500.0, 2400.0, 10000.0"
3,funded_amnt,float64,438,14.60%,No,Yes,"5000.0, 2500.0, 2400.0, 10000.0"
4,funded_amnt_inv,float64,663,22.10%,No,No,"4975.0, 2500.0, 2400.0, 10000.0"
5,term,category,2,0.07%,No,No,"36 months, 60 months, 36 months, 36 months"
6,int_rate,object,36,1.20%,No,No,"10.65%, 15.27%, 15.96%, 13.49%"
7,installment,float64,1591,53.03%,No,No,"162.87, 59.83, 84.33, 339.31"
8,grade,category,7,0.23%,No,No,"B, C, C, C"
9,sub_grade,category,35,1.17%,No,No,"B2, C4, C5, C1"
10,emp_title,object,2653,88.43%,Yes,No,"nan, Ryder, nan, AIR RESOURCES BOARD"
11,emp_length,category,11,0.37%,Yes,No,"10+ years, < 1 year, 10+ years, 10+ years"
12,home_ownership,category,3,0.10%,No,No,"RENT, RENT, RENT, RENT"
13,annual_inc,float64,641,21.37%,No,No,"24000.0, 30000.0, 12252.0, 49200.0"
14,verification_status,category,3,0.10%,No,No,"Verified, Source Verified, Not Verified, Sourc..."
15,issue_d,datetime64[ns],2,0.07%,No,No,"2011-12-01, 2011-12-01, 2011-12-01, 2011-12-01"
16,loan_status,category,6,0.20%,No,No,"Fully Paid, Charged Off, Fully Paid, Fully Paid"
17,pymnt_plan,category,1,0.03%,No,No,"n, n, n, n"
18,purpose,category,13,0.43%,No,No,"credit_card, car, small_business, other"
19,title,category,1406,46.87%,No,No,"Computer, bike, real estate business, personel"
20,zip_code,category,568,18.93%,No,No,"860xx, 309xx, 606xx, 917xx"
21,addr_state,category,43,1.43%,No,No,"AZ, GA, IL, CA"
22,dti,float64,1717,57.23%,No,No,"27.65, 1.0, 8.72, 20.0"
23,delinq_2yrs,float64,5,0.17%,No,Yes,"0.0, 0.0, 0.0, 0.0"
24,earliest_cr_line,datetime64[ns],366,12.20%,No,No,"1985-01-01, 1999-04-01, 2001-11-01, 1996-02-01"
25,inq_last_6mths,float64,9,0.30%,No,Yes,"1.0, 5.0, 2.0, 1.0"
26,open_acc,float64,29,0.97%,No,Yes,"3.0, 3.0, 2.0, 10.0"
27,pub_rec,float64,2,0.07%,No,Yes,"0.0, 0.0, 0.0, 0.0"
28,revol_bal,float64,2829,94.30%,No,Yes,"13648.0, 1687.0, 2956.0, 5598.0"
29,revol_util,object,884,29.47%,No,No,"83.7%, 9.4%, 98.5%, 21%"
30,total_acc,float64,62,2.07%,No,Yes,"9.0, 4.0, 10.0, 37.0"
31,initial_list_status,category,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float64,242,8.07%,No,No,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,242,8.07%,No,No,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,2985,99.50%,No,No,"5863.1551866952, 1008.71, 3005.6668441393, 122..."
35,total_pymnt_inv,float64,2801,93.37%,No,No,"5833.84, 1008.71, 3005.67, 12231.89"
36,total_rec_prncp,float64,1110,37.00%,No,No,"5000.0, 456.46, 2400.0, 10000.0"
37,total_rec_int,float64,2750,91.67%,No,No,"863.16, 435.17, 605.67, 2214.92"
38,total_rec_late_fee,float64,110,3.67%,No,No,"0.0, 0.0, 0.0, 16.97"
39,recoveries,float64,411,13.70%,No,No,"0.0, 117.08, 0.0, 0.0"
40,collection_recovery_fee,float64,364,12.13%,No,No,"0.0, 1.11, 0.0, 0.0"
41,last_pymnt_d,datetime64[ns],54,1.80%,Yes,No,"2015-01-01, 2013-04-01, 2014-06-01, 2015-01-01"
42,last_pymnt_amnt,float64,2847,94.90%,No,No,"171.62, 119.66, 649.91, 357.48"
43,last_credit_pull_d,datetime64[ns],55,1.83%,No,No,"2016-06-01, 2013-09-01, 2016-06-01, 2016-04-01"
44,collections_12_mths_ex_med,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
45,policy_code,float64,1,0.03%,No,Yes,"1.0, 1.0, 1.0, 1.0"
46,application_type,category,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
48,chargeoff_within_12_mths,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
49,delinq_amnt,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"
50,pub_rec_bankruptcies,float64,2,0.07%,No,Yes,"0.0, 0.0, 0.0, 0.0"
51,tax_liens,float64,1,0.03%,No,Yes,"0.0, 0.0, 0.0, 0.0"

[Back to Table of Contents](#toc)

By simply reassigning the data types for the majority of our object columns, we have reduced the total memory usage from **58.4 MB to 24.3 MB**. This is a significant improvement! We will now address the remaining numeric columns and refine the object columns that require more specific cleaning.

In [14]:
chunk_iter = pd.read_csv(
    'loans_2007.csv', 
    chunksize=3000, 
    dtype=improved_col_dtypes, 
    parse_dates=["issue_d", "earliest_cr_line", "last_pymnt_d", "last_credit_pull_d"],
    date_format='%b-%Y'
)

summaries = []
optimized_chunks = []
total_memory = 0

for chunk in chunk_iter:
    # Cleaning Specific Columns ('term', 'int_rate', 'revol_util')
    if 'term' in chunk.columns:
        term_cleaned = chunk['term'].str.strip().str.replace(' months', '')
        chunk['term'] = pd.to_numeric(term_cleaned, errors='coerce').astype('Int64')
        
    # int_rate and revol_util: Strip % and convert to float
    for col in ['int_rate', 'revol_util']:
        if col in chunk.columns and chunk[col].dtype == 'object':
            chunk[col] = chunk[col].str.rstrip('%').astype(float)

    # Logic-based Numeric Downcasting
    summary_df, _ = profile_chunk(chunk)
    
    for _, row in summary_df.iterrows():
        col = row['Column']
        dtype = str(row['Dtype'])
        has_missing = row['Has_Missing'] == 'Yes'
        is_int_candidate = row['Int_Candidate'] == 'Yes'
        
        if 'float' in dtype and has_missing:
            chunk[col] = chunk[col].astype('float32')
            
        elif is_int_candidate:
            chunk[col] = chunk[col].astype('int64')

    summary, footprint = profile_chunk(chunk)
    summaries.append(summary)
    total_memory += footprint
    optimized_chunks.append(chunk)

print(f"Optimization Complete!")
print(f"Total Memory Across Optimized Chunks: {total_memory:.2f} MB")
print("\n")
print("First Chunk:")
display(summaries[0])

Optimization Complete!
Total Memory Across Optimized Chunks: 20.27 MB


First Chunk:

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,object,3000,100.00%,No,No,"1077501, 1077430, 1077175, 1076863"
1,member_id,int64,3000,100.00%,No,No,"1296599, 1314167, 1313524, 1277178"
2,loan_amnt,int64,390,13.00%,No,No,"5000, 2500, 2400, 10000"
3,funded_amnt,int64,438,14.60%,No,No,"5000, 2500, 2400, 10000"
4,funded_amnt_inv,float64,663,22.10%,No,No,"4975.0, 2500.0, 2400.0, 10000.0"
5,term,Int64,2,0.07%,No,No,"36, 60, 36, 36"
6,int_rate,float64,36,1.20%,No,No,"10.65, 15.27, 15.96, 13.49"
7,installment,float64,1591,53.03%,No,No,"162.87, 59.83, 84.33, 339.31"
8,grade,category,7,0.23%,No,No,"B, C, C, C"
9,sub_grade,category,35,1.17%,No,No,"B2, C4, C5, C1"
10,emp_title,object,2653,88.43%,Yes,No,"nan, Ryder, nan, AIR RESOURCES BOARD"
11,emp_length,category,11,0.37%,Yes,No,"10+ years, < 1 year, 10+ years, 10+ years"
12,home_ownership,category,3,0.10%,No,No,"RENT, RENT, RENT, RENT"
13,annual_inc,float64,641,21.37%,No,No,"24000.0, 30000.0, 12252.0, 49200.0"
14,verification_status,category,3,0.10%,No,No,"Verified, Source Verified, Not Verified, Sourc..."
15,issue_d,datetime64[ns],2,0.07%,No,No,"2011-12-01, 2011-12-01, 2011-12-01, 2011-12-01"
16,loan_status,category,6,0.20%,No,No,"Fully Paid, Charged Off, Fully Paid, Fully Paid"
17,pymnt_plan,category,1,0.03%,No,No,"n, n, n, n"
18,purpose,category,13,0.43%,No,No,"credit_card, car, small_business, other"
19,title,category,1406,46.87%,No,No,"Computer, bike, real estate business, personel"
20,zip_code,category,568,18.93%,No,No,"860xx, 309xx, 606xx, 917xx"
21,addr_state,category,43,1.43%,No,No,"AZ, GA, IL, CA"
22,dti,float64,1717,57.23%,No,No,"27.65, 1.0, 8.72, 20.0"
23,delinq_2yrs,int64,5,0.17%,No,No,"0, 0, 0, 0"
24,earliest_cr_line,datetime64[ns],366,12.20%,No,No,"1985-01-01, 1999-04-01, 2001-11-01, 1996-02-01"
25,inq_last_6mths,int64,9,0.30%,No,No,"1, 5, 2, 1"
26,open_acc,int64,29,0.97%,No,No,"3, 3, 2, 10"
27,pub_rec,int64,2,0.07%,No,No,"0, 0, 0, 0"
28,revol_bal,int64,2829,94.30%,No,No,"13648, 1687, 2956, 5598"
29,revol_util,float64,884,29.47%,No,No,"83.7, 9.4, 98.5, 21.0"
30,total_acc,int64,62,2.07%,No,No,"9, 4, 10, 37"
31,initial_list_status,category,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float64,242,8.07%,No,No,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float64,242,8.07%,No,No,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,2985,99.50%,No,No,"5863.1551866952, 1008.71, 3005.6668441393, 122..."
35,total_pymnt_inv,float64,2801,93.37%,No,No,"5833.84, 1008.71, 3005.67, 12231.89"
36,total_rec_prncp,float64,1110,37.00%,No,No,"5000.0, 456.46, 2400.0, 10000.0"
37,total_rec_int,float64,2750,91.67%,No,No,"863.16, 435.17, 605.67, 2214.92"
38,total_rec_late_fee,float64,110,3.67%,No,No,"0.0, 0.0, 0.0, 16.97"
39,recoveries,float64,411,13.70%,No,No,"0.0, 117.08, 0.0, 0.0"
40,collection_recovery_fee,float64,364,12.13%,No,No,"0.0, 1.11, 0.0, 0.0"
41,last_pymnt_d,datetime64[ns],54,1.80%,Yes,No,"2015-01-01, 2013-04-01, 2014-06-01, 2015-01-01"
42,last_pymnt_amnt,float64,2847,94.90%,No,No,"171.62, 119.66, 649.91, 357.48"
43,last_credit_pull_d,datetime64[ns],55,1.83%,No,No,"2016-06-01, 2013-09-01, 2016-06-01, 2016-04-01"
44,collections_12_mths_ex_med,int64,1,0.03%,No,No,"0, 0, 0, 0"
45,policy_code,int64,1,0.03%,No,No,"1, 1, 1, 1"
46,application_type,category,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,int64,1,0.03%,No,No,"0, 0, 0, 0"
48,chargeoff_within_12_mths,int64,1,0.03%,No,No,"0, 0, 0, 0"
49,delinq_amnt,int64,1,0.03%,No,No,"0, 0, 0, 0"
50,pub_rec_bankruptcies,int64,2,0.07%,No,No,"0, 0, 0, 0"
51,tax_liens,int64,1,0.03%,No,No,"0, 0, 0, 0"

After further adjustments, our memory usage dropped from **24.3 MB to 20.3 MB**. While this decrease is less dramatic than the first round of optimization, every kilobyte counts in a memory-constrained environment. We have successfully made the dataset much more manageable.

[Back to Table of Contents](#toc)

### Downcasting Experiment
<a id="downcasting"></a>
As a final experiment, we will attempt to "downcast" every column in each chunk to its smallest possible subtype based on its actual values. While this may not always be practical in a production environment—as it can lead to inconsistent data types across different chunks—it serves as a great demonstration of the absolute minimum footprint we can achieve.

In [15]:
chunk_iter = pd.read_csv(
    'loans_2007.csv', 
    chunksize=3000, 
    dtype=improved_col_dtypes, 
    parse_dates=["issue_d", "earliest_cr_line", "last_pymnt_d", "last_credit_pull_d"],
    date_format='%b-%Y'
)

summaries = []
optimized_chunks = []
total_memory = 0

for chunk in chunk_iter:
    # Cleaning Specific Columns ('term', 'int_rate', 'revol_util')
    if 'term' in chunk.columns:
        term_cleaned = chunk['term'].str.strip().str.replace(' months', '')
        chunk['term'] = pd.to_numeric(term_cleaned, errors='coerce').astype('Int64')
        
    # int_rate and revol_util: Strip % and convert to float
    for col in ['int_rate', 'revol_util']:
        if col in chunk.columns and chunk[col].dtype == 'object':
            chunk[col] = chunk[col].str.rstrip('%').astype(float)

    # Logic-based Numeric Downcasting
    summary_df, _ = profile_chunk(chunk)
    
    for _, row in summary_df.iterrows():
        col = row['Column']
        dtype = str(row['Dtype'])
        has_missing = row['Has_Missing'] == 'Yes'
        is_int_candidate = row['Int_Candidate'] == 'Yes'
        
        if 'float' in dtype and has_missing:
            chunk[col] = chunk[col].astype('float32')
            
        elif is_int_candidate:
            chunk[col] = chunk[col].astype('int64')

    # Downcasting Experiment    
    float_cols = chunk.select_dtypes(include=['float']).columns
    int_cols = chunk.select_dtypes(include=['integer']).columns

    for col in float_cols:
        chunk[col] = pd.to_numeric(chunk[col], downcast='float')
    
    for col in int_cols:
        chunk[col] = pd.to_numeric(chunk[col], downcast='integer')

    summary, footprint = profile_chunk(chunk)
    summaries.append(summary)
    total_memory += footprint
    optimized_chunks.append(chunk)

print(f"Optimization Complete!")
print(f"Total Memory Across Optimized Chunks: {total_memory:.2f} MB")
print("\n")
print("First Chunk:")
display(summaries[0])

Optimization Complete!
Total Memory Across Optimized Chunks: 14.91 MB


First Chunk:

,Column,Dtype,Uniq_Count,Uniq_Pct,Has_Missing,Int_Candidate,Sample_Values
0,id,object,3000,100.00%,No,No,"1077501, 1077430, 1077175, 1076863"
1,member_id,int32,3000,100.00%,No,No,"1296599, 1314167, 1313524, 1277178"
2,loan_amnt,int32,390,13.00%,No,No,"5000, 2500, 2400, 10000"
3,funded_amnt,int32,438,14.60%,No,No,"5000, 2500, 2400, 10000"
4,funded_amnt_inv,float64,663,22.10%,No,No,"4975.0, 2500.0, 2400.0, 10000.0"
5,term,Int8,2,0.07%,No,No,"36, 60, 36, 36"
6,int_rate,float32,36,1.20%,No,No,"10.65, 15.27, 15.96, 13.49"
7,installment,float32,1591,53.03%,No,No,"162.87, 59.83, 84.33, 339.31"
8,grade,category,7,0.23%,No,No,"B, C, C, C"
9,sub_grade,category,35,1.17%,No,No,"B2, C4, C5, C1"
10,emp_title,object,2653,88.43%,Yes,No,"nan, Ryder, nan, AIR RESOURCES BOARD"
11,emp_length,category,11,0.37%,Yes,No,"10+ years, < 1 year, 10+ years, 10+ years"
12,home_ownership,category,3,0.10%,No,No,"RENT, RENT, RENT, RENT"
13,annual_inc,float64,641,21.37%,No,No,"24000.0, 30000.0, 12252.0, 49200.0"
14,verification_status,category,3,0.10%,No,No,"Verified, Source Verified, Not Verified, Sourc..."
15,issue_d,datetime64[ns],2,0.07%,No,No,"2011-12-01, 2011-12-01, 2011-12-01, 2011-12-01"
16,loan_status,category,6,0.20%,No,No,"Fully Paid, Charged Off, Fully Paid, Fully Paid"
17,pymnt_plan,category,1,0.03%,No,No,"n, n, n, n"
18,purpose,category,13,0.43%,No,No,"credit_card, car, small_business, other"
19,title,category,1406,46.87%,No,No,"Computer, bike, real estate business, personel"
20,zip_code,category,568,18.93%,No,No,"860xx, 309xx, 606xx, 917xx"
21,addr_state,category,43,1.43%,No,No,"AZ, GA, IL, CA"
22,dti,float32,1717,57.23%,No,No,"27.65, 1.0, 8.72, 20.0"
23,delinq_2yrs,int8,5,0.17%,No,No,"0, 0, 0, 0"
24,earliest_cr_line,datetime64[ns],366,12.20%,No,No,"1985-01-01, 1999-04-01, 2001-11-01, 1996-02-01"
25,inq_last_6mths,int8,9,0.30%,No,No,"1, 5, 2, 1"
26,open_acc,int8,29,0.97%,No,No,"3, 3, 2, 10"
27,pub_rec,int8,2,0.07%,No,No,"0, 0, 0, 0"
28,revol_bal,int32,2829,94.30%,No,No,"13648, 1687, 2956, 5598"
29,revol_util,float32,884,29.47%,No,No,"83.7, 9.4, 98.5, 21.0"
30,total_acc,int8,62,2.07%,No,No,"9, 4, 10, 37"
31,initial_list_status,category,1,0.03%,No,No,"f, f, f, f"
32,out_prncp,float32,242,8.07%,No,No,"0.0, 0.0, 0.0, 0.0"
33,out_prncp_inv,float32,242,8.07%,No,No,"0.0, 0.0, 0.0, 0.0"
34,total_pymnt,float64,2985,99.50%,No,No,"5863.1551866952, 1008.71, 3005.6668441393, 122..."
35,total_pymnt_inv,float64,2801,93.37%,No,No,"5833.84, 1008.71, 3005.67, 12231.89"
36,total_rec_prncp,float64,1110,37.00%,No,No,"5000.0, 456.46, 2400.0, 10000.0"
37,total_rec_int,float64,2750,91.67%,No,No,"863.16, 435.17, 605.67, 2214.92"
38,total_rec_late_fee,float32,83,2.77%,No,No,"0.0, 0.0, 0.0, 16.97"
39,recoveries,float64,411,13.70%,No,No,"0.0, 117.08, 0.0, 0.0"
40,collection_recovery_fee,float32,364,12.13%,No,No,"0.0, 1.11, 0.0, 0.0"
41,last_pymnt_d,datetime64[ns],54,1.80%,Yes,No,"2015-01-01, 2013-04-01, 2014-06-01, 2015-01-01"
42,last_pymnt_amnt,float64,2847,94.90%,No,No,"171.62, 119.66, 649.91, 357.48"
43,last_credit_pull_d,datetime64[ns],55,1.83%,No,No,"2016-06-01, 2013-09-01, 2016-06-01, 2016-04-01"
44,collections_12_mths_ex_med,int8,1,0.03%,No,No,"0, 0, 0, 0"
45,policy_code,int8,1,0.03%,No,No,"1, 1, 1, 1"
46,application_type,category,1,0.03%,No,No,"INDIVIDUAL, INDIVIDUAL, INDIVIDUAL, INDIVIDUAL"
47,acc_now_delinq,int8,1,0.03%,No,No,"0, 0, 0, 0"
48,chargeoff_within_12_mths,int8,1,0.03%,No,No,"0, 0, 0, 0"
49,delinq_amnt,int8,1,0.03%,No,No,"0, 0, 0, 0"
50,pub_rec_bankruptcies,int8,2,0.07%,No,No,"0, 0, 0, 0"
51,tax_liens,int8,1,0.03%,No,No,"0, 0, 0, 0"

### Conclusion
<a id="conclusion"></a>
Our experiment with downcasting yielded a final memory footprint of **14.91 MB**, down from our initial starting point of nearly 60 MB. Through the strategic use of chunking, converting strings to categorical data, and optimizing numeric types, we successfully reduced our memory usage by approximately 75%. This process demonstrates that even large datasets can be processed on modest hardware if the data types are managed with intent. While the final downcasting step is often avoided in real-world pipelines to maintain type consistency, the overall workflow provides a robust framework for handling data that exceeds available system memory.

[Back to Table of Contents](#toc)